### ISSUE TITLE
1.16.5: Enabling Bungee mode cause private message to dont work

### ISSUE THREAD

**Issue by Korinocho** [kangarko/ChatControl#1066]
On the last version (didnt test this before, I just started using now the plugin), if I enable the Bungee in the settings (after checking the server-name and in Bungee config.yml), and restarting the server, any /msg I try to send will say that "Player X is not online on this server" even if im trying to send it to myself like this:
![image](https://user-images.githubusercontent.com/21372197/121104654-e132d380-c7d8-11eb-85b3-0c446e695a09.png)

ChC ver: 10.4.6
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by Korinocho** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6612700/debug.zip)
This is my debug btw

**Comment by ElBananaa** [comment]
Hey!
Apparently you're using CMI.
As you can see on #960, turning off CMI chat system should fix the issue. Give it a try, and let me know if it fixes your issue :)

**Comment by Korinocho** [comment]
I never enabled CMI chat modules/system :/
Just double checked it and nothing:
Chat:
  Will try to modify chat to display it in defined format
  ModifyChatFormat: false

**Comment by kangarko** [comment]
I am closing this assuming the modifychatformat flag fixed it, if not comment below.

**Comment by Korinocho** [comment]
Nope, checked if the problem is CMI. Even without CMI plugin it wont work. Simply says that the user X is not online in this server :c

**Comment by ElBananaa** [comment]
> Nope, checked if the problem is CMI. Even without CMI plugin it wont work. Simply says that the user X is not online in this server :c

Hey!
Sorry to ear that, I'm reopening the issue since this isn't fixed yet. Unfortunately, Kangarko is on vacations until the 2nd of july, and I believe there isn't much I can do about your issue, so you'll have to wait until then.

**Comment by kangarko** [comment]
I am here, will handle this in 1-3 days.

**Comment by Korinocho** [comment]
No problem! If you need further info or testing contact me here or by discord (Korinocho#1313)

**Comment by kangarko** [comment]
Try setting UUID_Lookup to false/true to the other option from what you have now in your mysql.yml and see if the problem persists. Also ensure you're connecting to BungeeCord not directly to your Bukkit server

**Comment by Korinocho** [comment]
Alright. Will try in some hours on the dev environment

**Comment by Korinocho** [comment]
Still nothing.
This is what i checked in this order:
1. Both plugins installed (bungee/paper) (both last update)
2. Names in Bungee config.yml and server.properties
3. Removed all any other plugin, except these:
![image](https://user-images.githubusercontent.com/21372197/125137461-1afe3f00-e0e3-11eb-8fc3-0377bf2e72c7.png)
4. MySql connection is working good
5. Enabled BungeeCord
6. Enabled and disabled UUID_Lookup in mysql.yml (tried with both options)

Still getting this weird error that wont let anyone send Msg's

**Comment by Korinocho** [comment]
Now i set all the configs to 0. Started from nothing.
My steps to make msg's not work (stopped and started the server after each change):
1. Enabled: true (Channels) > Messages are disabled, so no problem here
2. Enabled: true (Private_Messages) > Messages works good:
![image](https://user-images.githubusercontent.com/21372197/125138162-87c60900-e0e4-11eb-84d5-9a5e38f0b7e3.png)
3. Enabled: true (BungeeCord) > Plugin wont load (needs MySql)
4. Configured MySql (UUID_Lookup: true by default) (MySql connection works good) > Sending Messages to anyone will say that X player is not online on this server (even myself)
5. Changing UUID_Lookup to: false > Same problem

Server.properties:
![image](https://user-images.githubusercontent.com/21372197/125138686-7a5d4e80-e0e5-11eb-8a55-033a26b3f5cf.png)
Bungee config.yml:
![image](https://user-images.githubusercontent.com/21372197/125138703-847f4d00-e0e5-11eb-8d35-8cb4ba5158c5.png)

Btw im using Waterfall and not pure Bungeecord.

**Comment by Korinocho** [comment]
Finally solved this. Had to delete all the Bungee folder and recreate it again (configs from 0 and so but with same plugins).
Maybe the .jar was faulty or some file from the config.
The things is that this was solved. Sorry for taking so much time.

**Comment by X-Niter** [comment]
> Finally solved this. Had to delete all the Bungee folder and recreate it again (configs from 0 and so but with same plugins).
> Maybe the .jar was faulty or some file from the config.
> The things is that this was solved. Sorry for taking so much time.

Okay so I don't want to reopen this issue but on 1.16.5 -> ChatControl-Red-10.5.4 -> BungeeControl-2.4.3, this issue persists. EXACTLY as the Korin fellow said, I followed exactly what they did and nothing changed. I am connecting from the proxy as I can't join directly due to firewall, the core server knows I'm coming from the proxy but nothing. 
I've even gone as far as deleting everything to even re-downloading the plugin completely. 

I have the same exact setup as Korin, using waterfall and paper latest updates that are currently out as of August 19 2021.

**Comment by ElBananaa** [comment]
> > Finally solved this. Had to delete all the Bungee folder and recreate it again (configs from 0 and so but with same plugins).
> > Maybe the .jar was faulty or some file from the config.
> > The things is that this was solved. Sorry for taking so much time.
> 
> Okay so I don't want to reopen this issue but on 1.16.5 -> ChatControl-Red-10.5.4 -> BungeeControl-2.4.3, this issue persists. EXACTLY as the Korin fellow said, I followed exactly what they did and nothing changed. I am connecting from the proxy as I can't join directly due to firewall, the core server knows I'm coming from the proxy but nothing.
> I've even gone as far as deleting everything to even re-downloading the plugin completely.
> 
> I have the same exact setup as Korin, using waterfall and paper latest updates that are currently out as of August 19 2021.

Hey!
I believe Kangarko put the wrong BungeControl jar file in the latest update. Switch back to ChatControlRed v10.5.3 and BungeeControlRed 3.5.3, and it should fix the issue.

**Comment by X-Niter** [comment]
> > > Finally solved this. Had to delete all the Bungee folder and recreate it again (configs from 0 and so but with same plugins).
> > > Maybe the .jar was faulty or some file from the config.
> > > The things is that this was solved. Sorry for taking so much time.
> > 
> > 
> > Okay so I don't want to reopen this issue but on 1.16.5 -> ChatControl-Red-10.5.4 -> BungeeControl-2.4.3, this issue persists. EXACTLY as the Korin fellow said, I followed exactly what they did and nothing changed. I am connecting from the proxy as I can't join directly due to firewall, the core server knows I'm coming from the proxy but nothing.
> > I've even gone as far as deleting everything to even re-downloading the plugin completely.
> > I have the same exact setup as Korin, using waterfall and paper latest updates that are currently out as of August 19 2021.
> 
> Hey!
> I believe Kangarko put the wrong BungeControl jar file in the latest update. Switch back to ChatControlRed v10.5.3 and BungeeControlRed 3.5.3, and it should fix the issue.

@ElBananaa - Thank you very much good fellow, doing just as you instructed fixed it!!
I would have never thought of doing that, thank you!

**Comment by ElBananaa** [comment]
> > > > Finally solved this. Had to delete all the Bungee folder and recreate it again (configs from 0 and so but with same plugins).
> > > > Maybe the .jar was faulty or some file from the config.
> > > > The things is that this was solved. Sorry for taking so much time.
> > > 
> > > 
> > > Okay so I don't want to reopen this issue but on 1.16.5 -> ChatControl-Red-10.5.4 -> BungeeControl-2.4.3, this issue persists. EXACTLY as the Korin fellow said, I followed exactly what they did and nothing changed. I am connecting from the proxy as I can't join directly due to firewall, the core server knows I'm coming from the proxy but nothing.
> > > I've even gone as far as deleting everything to even re-downloading the plugin completely.
> > > I have the same exact setup as Korin, using waterfall and paper latest updates that are currently out as of August 19 2021.
> > 
> > 
> > Hey!
> > I believe Kangarko put the wrong BungeControl jar file in the latest update. Switch back to ChatControlRed v10.5.3 and BungeeControlRed 3.5.3, and it should fix the issue.
> 
> @ElBananaa - Thank you very much good fellow, doing just as you instructed fixed it!!
> I would have never thought of doing that, thank you!

I'm glad it fixed the issue!
Kangarko plans to release another version today, you will probably be able to upgrade to this one ^^
Let me know if there's anything else I can do :)

**Comment by X-Niter** [comment]
> > > > > Finally solved this. Had to delete all the Bungee folder and recreate it again (configs from 0 and so but with same plugins).
> > > > > Maybe the .jar was faulty or some file from the config.
> > > > > The things is that this was solved. Sorry for taking so much time.
> > > > 
> > > > 
> > > > Okay so I don't want to reopen this issue but on 1.16.5 -> ChatControl-Red-10.5.4 -> BungeeControl-2.4.3, this issue persists. EXACTLY as the Korin fellow said, I followed exactly what they did and nothing changed. I am connecting from the proxy as I can't join directly due to firewall, the core server knows I'm coming from the proxy but nothing.
> > > > I've even gone as far as deleting everything to even re-downloading the plugin completely.
> > > > I have the same exact setup as Korin, using waterfall and paper latest updates that are currently out as of August 19 2021.
> > > 
> > > 
> > > Hey!
> > > I believe Kangarko put the wrong BungeControl jar file in the latest update. Switch back to ChatControlRed v10.5.3 and BungeeControlRed 3.5.3, and it should fix the issue.
> > 
> > 
> > @ElBananaa - Thank you very much good fellow, doing just as you instructed fixed it!!
> > I would have never thought of doing that, thank you!
> 
> I'm glad it fixed the issue!
> Kangarko plans to release another version today, you will probably be able to upgrade to this one ^^
> Let me know if there's anything else I can do :)

Roger that! I'll keep that in mind! I do have a side noted question just while I have you here; do y'all have plans on releasing a public discord, a place for potential admin <-> admin assisting each other and such! 
I was looking around for one but couldn't come up with anything unless it's under Mineacademy. :)

**Comment by ElBananaa** [comment]
> > > > > > Finally solved this. Had to delete all the Bungee folder and recreate it again (configs from 0 and so but with same plugins).
> > > > > > Maybe the .jar was faulty or some file from the config.
> > > > > > The things is that this was solved. Sorry for taking so much time.
> > > > > 
> > > > > 
> > > > > Okay so I don't want to reopen this issue but on 1.16.5 -> ChatControl-Red-10.5.4 -> BungeeControl-2.4.3, this issue persists. EXACTLY as the Korin fellow said, I followed exactly what they did and nothing changed. I am connecting from the proxy as I can't join directly due to firewall, the core server knows I'm coming from the proxy but nothing.
> > > > > I've even gone as far as deleting everything to even re-downloading the plugin completely.
> > > > > I have the same exact setup as Korin, using waterfall and paper latest updates that are currently out as of August 19 2021.
> > > > 
> > > > 
> > > > Hey!
> > > > I believe Kangarko put the wrong BungeControl jar file in the latest update. Switch back to ChatControlRed v10.5.3 and BungeeControlRed 3.5.3, and it should fix the issue.
> > > 
> > > 
> > > @ElBananaa - Thank you very much good fellow, doing just as you instructed fixed it!!
> > > I would have never thought of doing that, thank you!
> > 
> > 
> > I'm glad it fixed the issue!
> > Kangarko plans to release another version today, you will probably be able to upgrade to this one ^^
> > Let me know if there's anything else I can do :)
> 
> Roger that! I'll keep that in mind! I do have a side noted question just while I have you here; do y'all have plans on releasing a public discord, a place for potential admin <-> admin assisting each other and such!
> I was looking around for one but couldn't come up with anything unless it's under Mineacademy. :)

Yes, we do have a Discord server https://mineacademy.org/discord The server isn't public yet, however, if you don't mind giving us your discord tag (nick#id) we'd be more than happy to add you to a private channel in which we, as much as other server/plugin owners can assist you ^^

**Comment by X-Niter** [comment]
> > > > > > > Finally solved this. Had to delete all the Bungee folder and recreate it again (configs from 0 and so but with same plugins).
> > > > > > > Maybe the .jar was faulty or some file from the config.
> > > > > > > The things is that this was solved. Sorry for taking so much time.
> > > > > > 
> > > > > > 
> > > > > > Okay so I don't want to reopen this issue but on 1.16.5 -> ChatControl-Red-10.5.4 -> BungeeControl-2.4.3, this issue persists. EXACTLY as the Korin fellow said, I followed exactly what they did and nothing changed. I am connecting from the proxy as I can't join directly due to firewall, the core server knows I'm coming from the proxy but nothing.
> > > > > > I've even gone as far as deleting everything to even re-downloading the plugin completely.
> > > > > > I have the same exact setup as Korin, using waterfall and paper latest updates that are currently out as of August 19 2021.
> > > > > 
> > > > > 
> > > > > Hey!
> > > > > I believe Kangarko put the wrong BungeControl jar file in the latest update. Switch back to ChatControlRed v10.5.3 and BungeeControlRed 3.5.3, and it should fix the issue.
> > > > 
> > > > 
> > > > @ElBananaa - Thank you very much good fellow, doing just as you instructed fixed it!!
> > > > I would have never thought of doing that, thank you!
> > > 
> > > 
> > > I'm glad it fixed the issue!
> > > Kangarko plans to release another version today, you will probably be able to upgrade to this one ^^
> > > Let me know if there's anything else I can do :)
> > 
> > 
> > Roger that! I'll keep that in mind! I do have a side noted question just while I have you here; do y'all have plans on releasing a public discord, a place for potential admin <-> admin assisting each other and such!
> > I was looking around for one but couldn't come up with anything unless it's under Mineacademy. :)
> 
> Yes, we do have a Discord server https://mineacademy.org/discord The server isn't public yet, however, if you don't mind giving us your discord tag (nick#id) we'd be more than happy to add you to a private channel in which we, as much as other server/plugin owners can assist you ^^

Absolutely!
X_Niter#2563

And just from reading the channels, I totally get it, no hassle from me, just enjoy a nice chatting platform with other in regards to CC-Red. Loving this long reply thread! XD

**Comment by ElBananaa** [comment]
> > > > > > > > Finally solved this. Had to delete all the Bungee folder and recreate it again (configs from 0 and so but with same plugins).
> > > > > > > > Maybe the .jar was faulty or some file from the config.
> > > > > > > > The things is that this was solved. Sorry for taking so much time.
> > > > > > > 
> > > > > > > 
> > > > > > > Okay so I don't want to reopen this issue but on 1.16.5 -> ChatControl-Red-10.5.4 -> BungeeControl-2.4.3, this issue persists. EXACTLY as the Korin fellow said, I followed exactly what they did and nothing changed. I am connecting from the proxy as I can't join directly due to firewall, the core server knows I'm coming from the proxy but nothing.
> > > > > > > I've even gone as far as deleting everything to even re-downloading the plugin completely.
> > > > > > > I have the same exact setup as Korin, using waterfall and paper latest updates that are currently out as of August 19 2021.
> > > > > > 
> > > > > > 
> > > > > > Hey!
> > > > > > I believe Kangarko put the wrong BungeControl jar file in the latest update. Switch back to ChatControlRed v10.5.3 and BungeeControlRed 3.5.3, and it should fix the issue.
> > > > > 
> > > > > 
> > > > > @ElBananaa - Thank you very much good fellow, doing just as you instructed fixed it!!
> > > > > I would have never thought of doing that, thank you!
> > > > 
> > > > 
> > > > I'm glad it fixed the issue!
> > > > Kangarko plans to release another version today, you will probably be able to upgrade to this one ^^
> > > > Let me know if there's anything else I can do :)
> > > 
> > > 
> > > Roger that! I'll keep that in mind! I do have a side noted question just while I have you here; do y'all have plans on releasing a public discord, a place for potential admin <-> admin assisting each other and such!
> > > I was looking around for one but couldn't come up with anything unless it's under Mineacademy. :)
> > 
> > 
> > Yes, we do have a Discord server https://mineacademy.org/discord The server isn't public yet, however, if you don't mind giving us your discord tag (nick#id) we'd be more than happy to add you to a private channel in which we, as much as other server/plugin owners can assist you ^^
> 
> Absolutely!
> X_Niter#2563
> 
> And just from reading the channels, I totally get it, no hassle from me, just enjoy a nice chatting platform with other in regards to CC-Red. Loving this long reply thread! XD

Haha, yes, it's starting to be a very long thread 😄 
Kangarko added you to the channel 😉
