### ISSUE TITLE
1.16.5 Paper: On start, java.sql.BatchUpdateException related to improper SQL syntax

### ISSUE THREAD

**Issue by funnykeyboardsymbols** [kangarko/ChatControl#1217]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true (Velocity w/ SNAP! plugin)

```
[03:00:07 WARN]: java.sql.BatchUpdateException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ';INSERT INTO ChatControl (UUID, Name, Nick) VALUES ('4d92b9ee-07f8-43b9-a7fc-efd' at line 1
[03:00:07 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:00:07 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[03:00:07 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:00:07 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[03:00:07 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[03:00:07 WARN]:        at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
[03:00:07 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:167)
[03:00:07 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:174)
[03:00:07 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
[03:00:07 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatchUsingMultiQueries(StatementImpl.java:1031)
[03:00:07 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:839)
[03:00:07 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:794)
[03:00:07 WARN]:        at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.batchUpdate(SimpleDatabase.java:368)
[03:00:07 WARN]:        at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.insertBatch(SimpleDatabase.java:254)
[03:00:07 WARN]:        at org.mineacademy.chatcontrol.lib.database.SimpleDatabase.insertBatch(SimpleDatabase.java:234)
[03:00:07 WARN]:        at org.mineacademy.chatcontrol.model.Database.addUsersToMap(Database.java:483)
[03:00:07 WARN]:        at org.mineacademy.chatcontrol.model.UserMap.save(UserMap.java:149)
[03:00:07 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[03:00:07 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[03:00:07 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[03:00:07 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[03:00:07 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[03:00:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[03:00:07 WARN]: Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ';INSERT INTO ChatControl (UUID, Name, Nick) VALUES ('4d92b9ee-07f8-43b9-a7fc-efd' at line 1
[03:00:07 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[03:00:07 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[03:00:07 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:762)
[03:00:07 WARN]:        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:779)
[03:00:07 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatchUsingMultiQueries(StatementImpl.java:1017)
[03:00:07 WARN]:        ... 13 more

```

**Comment by kangarko** [comment]
I do believe this should be resolved in the next release.

If not, I made the error print all of the batch update commands to sql-error.log file that will be generated, so in case you will get it again just ZIP the file and upload it below and I have a look asap.

**Comment by funnykeyboardsymbols** [comment]
The issue persists after updating BungeeControl and ChatControl to 10.5.3
[sql-error.zip](https://github.com/kangarko/ChatControl-Red/files/6971728/sql-error.zip)

**Comment by kangarko** [comment]
I apologies, but after testing this and replacing {table} with ChatControl table name (make sure it is not called anything else or that it does not have spaces in it), it appears to be working from: https://www.eversql.com/sql-syntax-check-validator/

![a](https://i.imgur.com/8jkLSQ7.png)

Maybe it's your MySQL driver, try switching from MySQL to MariaDB or vice versa or using another version, also try changing the database collation to utf8mb4_unicode_520_ci
