### ISSUE TITLE
1.17.1: Silent join/leave messages

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1326]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

I have set both chatcontrol.silence.leave as chatcontrol.silence.join to true for moderators and myself. For moderators it seems to work and there doesn't show any leave or join message. For myself however, it keeps showing when I leave the server (only when unvanished, using premiumvanish). I am a bit lost and need assistance on what I do possibly wrong..

**Comment by ElBananaa** [comment]
Hey,
I just tried on a local fresh install, and I don't have this issue at all.
Both Chc-red and PremiumVanish have default settings.

Since you use PremiumVanish, I believe you should take a look at their config/permissions in order to fix your issue ^^

**Comment by Sikatsu** [comment]
Hmm, those settings are correct too, however meant for spigot servers.

I don't think that setting applies to bungee, as this setting is unable to hide join/quit messages from chatcontrolred's bungee section. It must be related to the above permissions, I think..

  # Should PV hide the real join/leave messages of invisible players?
  HideRealJoinQuitMessages: true

**Comment by kangarko** [comment]
Just to clarify, are we talking about the leave message setup on BungeeControl Red side on BungeeCord or ChatControl Red on your Spigot server? Please attach your debug log just so I can have a look where to find the bypass/require permission and reproduce myself asap.

**Comment by Sikatsu** [comment]
On the BungeeControl red side, how can I get a debug zip from BungeeControl?

**Comment by Sikatsu** [comment]
Even though I joined in vanish:
![image](https://user-images.githubusercontent.com/5664135/134439228-086b01d4-395f-4179-a6c8-815b1f62f4c7.png)

But after relogging, it didn't show it again.
I have a feeling those permissions are not always working correctly.. (or it doesn't always catch and hide the login/logout messages?)

**Comment by kangarko** [comment]
You cannot get an automatically compiled file there, you'd have to manually just zip your folder.

That's strange though, what permissions plugin are you using on bungee?

**Comment by Sikatsu** [comment]
We are using LuckPerms. It seems to sometimes fail to catch this permission and still show my leave message :/

**Comment by kangarko** [comment]
In the next release, set Debug to [operator] in the console, and let me know the messages when it should silence your join/leave message but it does not.

**Comment by Sikatsu** [comment]
It happened within this debug: https://pastebin.com/D3QsPSBD

**Comment by TheIntolerant** [comment]
I haven't tested this on the latest version yet. However, I was also having the same issue.

So just for context, basically all my staff join each server in vanish (we use PremiumVanish) and it seems the join/switch/leave message would only show up if the user was unvanished. When I tested this using the debug thing, I noticed if a user was in vanish, I wasn't getting these logs
```
>.... [16:26:13 INFO]: [BungeeControl-Red] FILTERING main_message
>.... [16:26:13 INFO]: [BungeeControl-Red] CAN FILTER message main_message
```
etc....
in the console, this changed as soon as the user was out of vanish and switched/joined/quit a server. In which case the messages would appear as intended.

NOTE:
I am also talking about the messages on BungeeControl-Red and I am also using the perms from the default message files.
P.S. Besides a few minor changes to the actual format of the messages, my messages for BungeeControl-Red are pretty much the same as the default files.

**Comment by TheIntolerant** [comment]
I assume this has something to do with how premium vanish works on bungee?

**Comment by ElBananaa** [comment]
Well, I don't really know much about your issue, however I never had this issue on any of my servers, not even my official test server, or my prod servers, which are all paper servers.

**Comment by kangarko** [comment]
Will follow up on this in 1-2 days.

**Comment by kangarko** [comment]
I have increased the delay we use to wait for Bukkit to report if player is vanished from 0.2 to 0.5s on BungeeControl Red. Let me know below when you will still experience this issue on the next version,.

**Comment by TheIntolerant** [comment]
@kangarko, I should probably mention this, I am still having the issue of join/switch/quit messages not showing for users who are vanished.

With the updated version I did notice a few times the messages would come though this was very minimal and most of the time the messages wouldn't send if the user was in vanish.

**Comment by kangarko** [comment]
@gone-incognito really odd, I will be putting this into our backburner right now since I have other things on the table such as Boss release, but let me know if it gets worsened or fixed in the next release and I'll follow up asap

**Comment by TheIntolerant** [comment]
So far the issue seems to be persistent. However, after the change you've made which was mentioned above, it appears that the join messages have improved (this however is still not showing up consistently, at least 3 out of 10 times, it would display the message if the user was in vanish). These changes do not seem to have any effect on the other "switch" and "quit" messages unfortunately. Meaning the only messages that seems to go through (￼occasionally) is the join message if the user is in vanish.

For testing ￼purposes, I should mention that vanish on join, for my staff is toggled with the premium vanish command 
"/networkvanish" which is only￼ available if you have premium vanish installed on all backend servers as well as the proxy server.￼

**Comment by kangarko** [comment]
@gone-incognito please DM me your email over Discord and I'll add you to our repo, you can have a look at how we wait for the data from bukkit and maybe you can help. I have tweaked the delays and periods for this task, please also test the next version.

**Comment by TheIntolerant** [comment]
It might also be worth noting this, so prior to 10.6.0 Beta, this issue was nonexistent. However due to the change:
**Removed | Removed deprecated old Messages sending in BungeeControl Red.**

I had to start using the new message system on BungeeControl-Red. As soon as I updated the plugin after this particular change, I encountered the issue with users in vanish, not having their join/switch/quit messages not coming through.


Also I have see no noticeable changes since updating to version **10.7.5** regarding this issue.

**Comment by kangarko** [comment]
The old system did not need any data from Bukkit, this is different.

Just tested with PremiumVanish without using their MySQL mode (could not get this to work), I tested like 10 times and it consistently hid join/leave messages if the player was vanished (through /vanish, not /networkvanish). Is this the prefered output? Let me know what I did wrong.

![a](https://i.imgur.com/230Giio.png)

**Comment by TheIntolerant** [comment]
Yeah, so the usage of /networkvanish, was a recent change I made on our network.

I should of been more clear, so I guess I was wondering if it is possible via an operator or something, to make it so the messages do no need any data from bukkit but instead just does all the permission checks on bungee like before.

So if it is possible to make an operator which makes it so only permission checks are done on bungee￼/proxy server, I feel this would most likely fix the issue.

P.S. sorry if this is not doable, unfortunately my experience with Java at this point in time is nonexistent. So I am unsure of what is actually possible.

**Comment by kangarko** [comment]
@gone-incognito sorry that this shitty bug is taking this long. Give your vanished staff the "chatcontrol.bypass.reach" permission on the next version, I made a change that it should force the message to appear if the sender has that given permission. Let me know how it goes!

**Comment by TheIntolerant** [comment]
Just updated and it seems to be working great now!

Just curious though @kangarko...

So just for argument sake, let's say I had a group called member and they had access to /vanish as a perk but I didn't want them to have the ability to bypass /ignore but also wanted to ensure all their join/switch/quit messages worked regardless if they did /vanish 

If I typed

**/lp group member permission set chatcontrol.bypass.reach true server=proxy** 

Which assigns the permission to the bungee server only, our member group wouldn't have the ability to bypass /ignore etc right? As the permission checks done to bypass /ignore are performed on the backend servers (running on spigot/paper etc.)

Right?

That was the only concern I have with that specific perm being used to make sure peoples join/switch/quit messages go through on bungeecontrol-red, as other users may allow non-staff to use /vanish and may accidentally assign it globally instead of just to their proxy server, otherwise all is working wonderfully!!

**Comment by kangarko** [comment]
Glad to hear it worked!

Regarding the perk, unfortunately we do not have that split. If you give users the bypass permissions, they will be able to bypass ignore. But if you only give the "bypass" permissions to them on BungeeCord and not on Spigot/Paper, then we should continue blocking their /ignore access regardless.
