### ISSUE TITLE
Ironically, players are using /thru and changing channels to spam chat using Chat Control!

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1681]
Funny enough, players are using chat control to spam the chat, super ironic for ChatControl.
They are using the message that gets shown in chat when you join/leave a chat channel and also /thru to spam the chat with these messages.

1. Can you just detect when someone does this on purpose like you do with other parts of your plugin to detect they are spamming it on purpose.
2. Is there a permission to show/hide it for certain groups
3. Can you not use the command /thru, this is a very handy worldedit command to go through a block, its very odd that its been overtaken by ChatControl!

Thanks!

**Comment by ElBananaa** [comment]
Hey,

1. You should be able to prevent user from abusing the join & leave commands using our command antispam feature.

2. There's no permission to show/hide channel join/quit messages. However, you can disable these messages by setting `Notification: ''` for both the join & quit messages.

3. I am completely unable to reproduce this issue on a completely fresh setup with default permissions & files. Actually, there's absolutely no sign of any `/thru` command in any of the default files, which means that either you didn't properly setup one of your custom rules, or your permission setup is bad, but anyways, there's nothing we can do about this, it's definitely looks like an issue on your side, which we can't fix for you.


Since you didn't follow the bug-report format, I don't have any information about either the plugins installed, the server version, the plugin version, the java version, the server software used and the plugins versions, so here are mine.

__**Next time, please follow the format.**__

```
Version: git-Purpur-1533 (MC: 1.18.1)
Java: 17
MySQL: No
Chc-red 10.9.5, Luckperms v5.3.98, Vault 1.7.3, ProtocolLib b540, WorldEdit 7.2.8
```

**Comment by TomLewis** [comment]
Hi Banannaa

1. `Using our command antispam feature.` So putting a cooldown on how often players can join and leave a channel? I dont want to limit the use, I just want to limit how often the message is spammed in chat! I dont want to have to fix this by limiting the use of switching channels.
2. There should be a permission added! I suggest that is created then!
3. Looks like I found a new bug then with your "custom command" system! I created /th as a toggle command using the syntax specified in the Wiki here to create a toggle. I already requested a proper #1599 to resolve this very complicated system, that would have solved it, looks like its creating more problems! 
So it looks like ANYTHING after the /th I setup is running as a command, in this case /thru, so what its doing is actually breaking other plugins commands because there is no toggle system!
```

# This rule only executes when player is not in the admin channel for reading.
match ^(\/th)
dont verbose
ignore channel helpop write
then command channel join helpop write
then deny

# This rule only executes when player is in the admin channel for writing.
match ^(\/th)
dont verbose
require channel helpop write
then command channel join global write
then deny

```

**Comment by TheIntolerant** [comment]
Hey, so this issue with /thru is being caused by an improper rule setup, I've updated [custom-commands wiki](https://github.com/kangarko/ChatControl-Red/wiki/Tab-completing-custom-commands) to address this and instead of using ``^(\/ach)``, its been changed to ``^(\/ach)$``.

The regex ``^(\/th)`` will match ``/thru`` so, therefore, you should change it to ``^(\/th)$`` and then /thru will work like normal.

**Comment by TomLewis** [comment]
Thanks, what about the helpop example?
```
#Catch "/helpop" command and send usage.
match ^\/helpop$
dont verbose
then warn &cDescription: Send a message to online staff members.
then warn &cUsage: /helpop <message>
then deny

#Catch "/helpop <message>" and redirect to the helpop channel.
match ^(\/helpop) (.*)
dont verbose
then command channel send helpop $2
then deny

#Catch "/h" command and send usage.
match ^\/h$
dont verbose
then warn &cDescription: Send a message to online staff members.
then warn &cUsage: /helpop <message>
then deny

#Catch "/h <message>" and redirect to the helpop channel.
match ^(\/h) (.*)
dont verbose
then command channel send helpop $2
then deny
```

**Comment by TheIntolerant** [comment]
That regex seems fine, I don't see it being problematic.

**Comment by kangarko** [comment]
I have a feel the questions have been addressed, let me know below if you still need our/my help and point me to the relevant parts of the conversation, thank you and thanks to our team for helping out!

**Comment by TomLewis** [comment]
No, the main issue is not resolved.

Its not even been addressed.
Number 1, peolpe are spamming changing channels to SPAM chat using chatcontrol.

> Can you just detect when someone does this on purpose like you do with other parts of your plugin to detect they are spamming it on purpose.

**Comment by kangarko** [comment]
Well with the same logic we'd have to implement "anti-abuse" features for all commands, including those from other plugins right? What about spamming the other dozens of commands from all of the other plugins?

With that in mind, it makes more sense to crease a universal "anti-abuse plugin" compatible for any command, not just channel join/leave ones.

Have you looked into a third party plugin that does this? Possibly some "cooldown" plugin or similar? Albeit more complex, that would give you a more powerful tool than anything I could ever add :)

I do think these plugins exist already!

**Comment by TomLewis** [comment]
What? I dont have issues from any other plugins spamming chat.

Only ChatControl Red when people join & leave channels, because you didnt consider it would be abused (lack of testing on real servers with active players) 

This is suppose to be a plugin to help reduce spam, not create it. Why is this such a battle? 
you already have systems to check for spam, just hook into one of those.

**Comment by kangarko** [comment]
I could add a cooldown to join the same channel again by a player command, would that work?

**Comment by kangarko** [comment]
Maybe add a "playerdelay" operator to rules:

```
match /channel (join|leave)
ignore player delay 5 seconds
then warn Please wait 5 seconds before issuing this command again.
```

Would that work?

**Comment by TomLewis** [comment]
> I could add a cooldown to join the same channel again by a player command, would that work?

No, we dont want to interfere with actual use of the channels, just reduce the message output in chat.
A lot of players use /ch and click to try and understand how the channel system works, so we definitally do not want to make it even more tedious to understand.

Its just the output message thats sent in chats when peolpe join/leave needs to have a setting that if peolpe go in and out very fast that the message in chat to say they have joined/left is not sent.

**Comment by TheIntolerant** [comment]
> Maybe add a "playerdelay" operator to rules:
> 
> 
> 
> ```
> 
> match /channel (join|leave)
> 
> ignore player delay 5 seconds
> 
> then warn Please wait 5 seconds before issuing this command again.
> 
> ```
> 
> 
> 
> Would that work?

Something like this would address this issue #1629 though.

**Comment by kangarko** [comment]
I've added "Channel.Antispam_Broadcast_Threshold" option to the next release :)

**Comment by TomLewis** [comment]
> I've added "Channel.Antispam_Broadcast_Threshold" option to the next release :)

Fantastic, thank you. Im not sure why players feel the need to always try and spam absolutly everything. 

Feels like a constant battle.

**Comment by kangarko** [comment]
We're here to help! But that's probably a deeper issue, putting bandages over broken stuff is a never ending story.

There's ways I saw people deal with inappropriate users, from straight up strict rules enforcements leading to permanent bans, to interesting incentives such giving negative points and not allowing vote rewards to be claimed when users have negative points, to simply creating "senior" chat channels with manual approval for verified members and leaving the garbage on the main thread which is opt-out-able.

**Comment by TomLewis** [comment]
I for one would love to read more about how other servers have setup systems like that, not sure where the medium is or how you collate this information but sharing is always helpful to others!

**Comment by kangarko** [comment]
Just private, infrequent talks with server owners. I am actually preparing a new Week to my training program on running a network where I consolidate this info.

Let me know what problems you have as a server owner in bullet points below and I'll give you free access ;)
