### ISSUE TITLE
1.18.2: Up to 4x join/switch messages on Bungee

### ISSUE THREAD

**Issue by MADS0LADEN** [kangarko/ChatControl#1890]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

https://i.imgur.com/81y5z9M.png

After i updated to the latest version it sends the join/switch messages multiple times in a row

**Comment by x1p** [comment]
Same here.
All broadcasts like mutes, bans and `chc forward bungee` are send once, twice, three of four times.
I was investigating this yesterday on a test bungee + server but I couldn't replicate it. It seems to happen pretty random.
Reverted back to version 10.11.0 since this was the last stable version for me.

**Comment by TheIntolerant** [comment]
Most likely related to #1887

**Comment by kangarko** [comment]
Thanks, investigating

**Comment by kangarko** [comment]
Should be resolved, I do apology for this annoying issue.

**Comment by x1p** [comment]
After running almost 20 hours I have to inform you that it's not solved.
After 12 hours it began doubling again, then 3 messages, now it's 4 messages.

**Comment by TheIntolerant** [comment]
Can confirm, unfortunately.

**Comment by kangarko** [comment]
I am sorry, please test the next release. Let me know how many players were online plus how many servers are connected.

**Comment by itsBeaco** [comment]
I'm on the latest release for both CCR & VelocityControl and the issue still occurs for me. I have 5 servers connected and this is after the latest restart:

![image](https://user-images.githubusercontent.com/77558094/169710937-486037d0-b36b-4512-8305-09c934f143fa.png)

If I can provide any further information to help, please let me know!

**Comment by itsBeaco** [comment]
Not sure if it's related to the join game and switch messages but when people switch channels, they get multiple messages as well: 

![image](https://user-images.githubusercontent.com/77558094/169711173-2e4665b7-f53c-4724-a372-b7bdcc89ad7a.png)

I'm on the latest version of CCR & VelocityControl. Currently have 5 servers connected and around 30 players online.

If I can provide any further information, please let me know. Sorry if it's an unrelated issue, let me know and I can report separately. Thank you in advance!

**Comment by kangarko** [comment]
Thanks, probably seems related, going to investigate asap

**Comment by TheIntolerant** [comment]
A similar issue was reported on discord ![image](https://user-images.githubusercontent.com/48093184/169927660-76368f57-ed37-4ad8-af50-d18676a1dc3d.jpeg)

**Comment by Sikatsu** [comment]
I have this issue as well. Attaching an error log too.

![image](https://user-images.githubusercontent.com/5664135/170104448-0f1b6353-050c-4320-b60e-f56e9317a597.png)

[error_log.log](https://github.com/kangarko/ChatControl-Red/files/8765276/error_log.log)

**Comment by kangarko** [comment]
Fixed.

REALLY REALLY strange, or I am misunderstanding something. I have switched from Player#sendBungeeMessage to Server#sendBungeeMessage since both implement this interface that we use: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/plugin/messaging/PluginMessageRecipient.html#sendPluginMessage(org.bukkit.plugin.Plugin,java.lang.String,byte%5B%5D)

Possible cause might be that the server got registered multiple times? I have no idea, not having the time right now to debug this but I am thankful to say it has been patched. Sorry for the delay, took longer to find since that was completely unrelated and extremely hidden: https://github.com/kangarko/Foundation/commit/371d47eb6600db7226c53a7c871860329c34d9a2
