### ISSUE TITLE
1.19 Lands can't connect to MySQL database when ChatControl-Red is installed

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1961]
I'm using the land claiming plugin called Lands. After installing ChatControl-Red the Lands plugin can't connect to the MySQL database anymore and is therefore disabled. When I remove this plugin, this issue goes away and there is no database problems. 

Note: This is a new issue caused by a recent update to this plugin, I'm not sure which one. I did not have this issue with 10.11.5.

Minecraft Version: 1.19
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey,
Please provide us your `/chc debug` file, and your latest.log file.

**Comment by kangarko** [comment]
Use the latest ChatControl release, we've fixed an issue with our database closing the main pool. I apology.

**Comment by ghost** [comment]
The issue still exist using the lastest version


Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
