### ISSUE TITLE
1.18.2: "then discord" rule operator fails to send to discord, logs stack trace to console (offlineSender is null)

### ISSUE THREAD

**Issue by waseric** [kangarko/ChatControl#2123]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/49cf27a96af0486f94edab05f04d6901

### "/chc debug" output (strongly recommended)

from command.rs:
```yaml
# -----------------------------------------------------------------------------------------------
# Private Message logging
# -----------------------------------------------------------------------------------------------

match ^\/m\s|^\/message\s|^\/msg\s|^\/pm\s|^\/r\s|^\/reply\s|^\/t\s|^\/tell\s|^\/w\s|^\/whisper\s
then discord numericchannelid [PM] {player}@{server_name}: {original_message}
then write logs/messages.log [PM] {player}@{server_name}: {original_message}
dont verbose
```

from anvil.rs:
```yaml
match \S
then discord numericchannelid [ANVIL] {player}: {server_name}/{world} @ {x} {y} {z} [ITEM] {original_message}
then write logs/anvil.log [ANVIL] {player}: {server_name}/{world} @ {x} {y} {z} [ITEM] {original_message}
dont verbose
```

### Information about the issue/bug

When using "then discord" operator in a rule to log messages to discord channel, a warning and stack trace are made on the console, indicating that offlineSender is null.  The message is not sent to the discord channel, but subsequent operators (e.g. "then write <file> ...") do succeed.

This behavior was first observed in 10.13.9, is present in 10.13.10, and is being worked around by a rollback to 10.13.7.

Channels with associated Discord_Channel_Id are NOT affected -- messages to a channel continued to go to discord just fine.

**Comment by ElBananaa** [comment]
I can also reproduce. @relavis

**Comment by UserDerezzed** [comment]
Thanks for the report, I will take a look at this ASAP. Definitely caused by my commit.

**Comment by kangarko** [comment]
I fixed this right now

**Comment by waseric** [comment]
I'm sorry to say this issue has not been fixed.
The stack trace has changed, but all other elements of the report are still the same in 10.4.1.

```
[19:59:34 WARN]: java.lang.NullPointerException
[19:59:34 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.model.Discord.lambda$sendChannelMessage$1(Discord.java:226)
[19:59:34 WARN]:        at ChatControl-Red.jar//org.mineacademy.chatcontrol.model.Discord$$Lambda$10750/0x00000000be7bcd20.run(Unknown Source)
[19:59:34 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[19:59:34 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:59:34 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:59:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:59:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:59:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:884)
```

**Comment by kangarko** [comment]
Sorry going to re-fix this again tonight asap!
