### ISSUE TITLE
[Issue] Private messages are being sent as someone else

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#222]
This one might need debugging, I am not entirely sure what you need though.

My moderator ''camerahoofd'' sent this message, but in spy we could see that it shows as if ''Gerard_De_Cutie'' sent this message.

![image](https://user-images.githubusercontent.com/5664135/101089630-b8295000-35b5-11eb-95e7-3b6e4bc25f85.png)

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

**Comment by Sikatsu** [comment]
![Screenshot_20201204-205557](https://user-images.githubusercontent.com/5664135/101208993-4a435e00-3673-11eb-8745-d23ec0b83036.jpg)

**Comment by NerdyBirder** [comment]
We are having the same issue on my bungeecord server.

**Comment by Sikatsu** [comment]
I think this mostly happens with /r and not with the initial private message command /msg

**Comment by ElBananaa** [comment]
I tried, but it looks like I can't reproduce it. I guess it's related to mysql.

Paper 1.16.4
Java 14
No bungee
No MySQL

**Comment by Sikatsu** [comment]
Sometimes /r no longer works and you somehow have to use /msg again. Seems the /r command has some issues over bungee.

**Comment by kangarko** [comment]
Investigating right now. I found that the same 30-minute expiration policy causing channels to disconnect was set for the sender cache too, which was responsible for some private messages-related data. I will fix that bug to the next version. Please comment below if you will still have this issue.

**Comment by Sikatsu** [comment]
Will do, this is a nasty bug and seems only related to /reply.

**Comment by Sikatsu** [comment]
@kangarko Sadly this doesn't seem fixed, /reply is still bugged and shows the wrong player names.

![image](https://user-images.githubusercontent.com/5664135/101290693-3ed36c80-3804-11eb-947a-1cd58fd6ee83.png)

**Comment by kangarko** [comment]
Test the next version please. I cannot reproduce this, unfortunately. If you find what specific steps trigger the bug, such as doing /chc reload or similar, please let me know.

**Comment by Sikatsu** [comment]
It's not related to any command like /chc reload, it just happens with the /reply command. This was also an issue on ChatControl 8 (and also 9, which we don't speak off) it was fixed in a later release however.

In the image below somehow the message from Fiddlestok shows to camerahoofd as if he sent it to himself (and therfor duplicates too in this case)

![image](https://user-images.githubusercontent.com/5664135/101346240-91566c80-3888-11eb-9706-84ca39a5f7dd.png)

**Comment by kangarko** [comment]
Please wait a little bit and test on 10.1.7. 

What setup do I need to reproduce this? Two servers, three players, assuming two are on server 1 and the third is on server 2 messaging each other? In what sequence?

**Comment by Sikatsu** [comment]
I will test on 10.1.7 of course! We have three servers under bungee. But this also happens when you are on the same server, so you don't HAVE to be on a differen server either. Other then that, it's totally random as of why and when it happens. Lets say it works 90% of the times correctly, and the other 10% it mixes the names up for some reason. This is exactly why it's hard to reproduce, but easier to be found on a production server.

**Comment by kangarko** [comment]
Thanks for letting me know, will continue investigating!

**Comment by Sikatsu** [comment]
This sadly still occurs. 

![image](https://user-images.githubusercontent.com/5664135/101373278-0e93d880-38ad-11eb-8656-c4cfd50e13d5.png)

**Comment by ElBananaa** [comment]
> This sadly still occurs.
> 
> ![image](https://user-images.githubusercontent.com/5664135/101373278-0e93d880-38ad-11eb-8656-c4cfd50e13d5.png)

Could you give us your `/plugins/ChatControlRed/formats/pm-receiver` and you `/plugins/ChatControlRed/formats/pm-sender` files?

I still can't reproduce your issue, so I guess this is related to the format ^^

**Comment by kangarko** [comment]
@Sikatsu what about if you use the default PM format as @ElBananaa has suggested?

**Comment by Sikatsu** [comment]
The issue is hard to reproduce as it only happens sometimes. I can't currently test the default PM format though, that would have to be later.

Attaching my current format:
[PM.zip](https://github.com/kangarko/ChatControl-Red/files/5673540/PM.zip)

**Comment by kangarko** [comment]
I understand, I am short on time now so I havent looked into your ZIP but can you try at least using the same variables for sender/receiver as from our default files?

**Comment by Sikatsu** [comment]
Yeah I can try, the variables seem to be about the same though!

**Comment by Sikatsu** [comment]
This is a default variable:

![image](https://user-images.githubusercontent.com/5664135/101790277-9161a100-3b02-11eb-9799-9fbf561e38dc.png)

**Comment by ElBananaa** [comment]
Hummm, your files looks right, that's weird...

For the variable, this is what I use, and it works fine.
```
Type: format

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand"
Key: receiver_or_you

# The value the key will be replaced to.
# This uses JavaScript and must return a boolean value.
Value: '''{player}'' == ''{player}'' ? ''you'' : ''{receiver}'''

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: ''

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

# See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
# and only show the message to those receivers for which the condition returns true.
Receiver_Condition: ''

# What permission must the message receiver have in order for this variable to display to them?
Receiver_Permission: ''
```

**Comment by kangarko** [comment]
Yeah you can just install that variable to variables/ and let me know if the problem still occurs.

2. Also please leave Show_Tips on true and let me know if the bug is also visible on this console message: https://i.imgur.com/bCpGCh9.png

3, Finally, is the bug visible in /chc log?

**Comment by Sikatsu** [comment]
I added that format in variables/ and used it in the PM formatting now.

`Value: '''{receiver}'' == ''{player}'' ? ''&eIk'' : ''{receiver}'''`

Show_Tips is enabled (never was disabled), I went back in the logs and this is a conversation between sil_20005 and bearly_awake, however mid-conversation the message goes to bearly_awake himself rather then sil_20005:

https://pastebin.com/X27rMVJA

**Comment by Sikatsu** [comment]
Well, this still occurs even with the above variable.


Output from /chc log, the player Ice_Walloww_Come was having a conversation with dennis0770: 

![image](https://user-images.githubusercontent.com/5664135/101992255-2a82ea00-3cb2-11eb-8a8c-6ab44bd58b0e.png)
![image](https://user-images.githubusercontent.com/5664135/101992258-2f479e00-3cb2-11eb-94fc-25a4463f7053.png)

So the players ZaWoo, JoopieJoopie, himself all got in between his conversation and the player thought he was being trolled by staff. Shows that this matter is quite important, I don't understand how I am the only one with this issue (altho there has been reports about it before) then again, I believe not many run this on production yet. And I couldn't find this on a test server myself either.

**Comment by kangarko** [comment]
@Sikatsu sorry for the delay... I'll be working on a fix however it's going to take a few extra days.

**Comment by Sikatsu** [comment]
For what I see and hear it's indeed only /r. Hope it'll be solved soon, players are getting annoyed by now haha

**Comment by kangarko** [comment]
I implemented a brand new packet and did some edits.. blindly, because I could not reproduce the bug, but at least isolated it to the /reply command. There were two calls to update the reply player and I reduced this to one, hopefully these changes will now fix the problem. 

Feel free to reopen in case you experience something! I also changed the tip message in the console to include /tell and /reply so you will be 100% sure where this is coming from.

**Comment by Sikatsu** [comment]
I'm very sorry but /r is still bugged, I was talking to my girlfriend. The message ''Like 4'' was sent by her, not by me. The message ''We didn't even call today'' was sent by me, but I am also the receiver. It kinda feels like this happens when you message at the same time. However, it's definitely not fixed on todays release. :(

![image](https://user-images.githubusercontent.com/5664135/102541806-2ccdb580-40b1-11eb-9a09-bcb1500241b3.png)

**Comment by kangarko** [comment]
Fuck, going to do another deep dive. So far the only thing preventing me from fixing this fully is actually reproducing this. Will try simulating the situation when two people are messaging at the same time. At least we know it's only affecting /reply not /tell.

**Comment by aerulion** [comment]
I probably just had the same bug occuring on an different server, maybe this information will help:

1) Person A sent a message to Person B
2) Person A sent a message to Person C
3) Person C used /r to answer Person A
4) Person B's chat showed that he sent the message (that Person C typed) to Person A, while Person A also received the message in the name of Person B
5) Person C's chat didn't show anything at all

~aerulion

**Comment by TheoRetisch1** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5731682/debug.zip)
We experience this problem on a daily basis. ChatControlRed was easy to understand, easy to set up and was well tested before it was released. However, this one bug is quite annoying and irritates players a lot, I hope for a fix in the near future :)

**Comment by kangarko** [comment]
So sorry, this is being worked on, it's one of the few 1-2 long-term issues we have recorded, pretty sure we can get this fixed when I sit down for 4-8 hours and debug this properly tomorrow or in a bit.

**Comment by TheoRetisch1** [comment]
Thanks for your effort 👍

**Comment by kangarko** [comment]
@Sikatsu @TheoRetisch1 I made the following changes to the next version:

1. Added a special flag that's on during the entire handling of a PM during which the sender can't send any more PM's. Same goes for the receiver. Should only be noticeable when sending PM's at the same time, this is the time when the bug may occur so we try to avoid situations like these.

2. Fixed debug messages that now correctly show reply/tell debug output:

`[ChatControlRed] /reply [kangarko -> kangarko]: test`

Please let me know when you experience that bug again with the log messages attached with explanation where these went broken. Thanks, pretty sure we can get solved this fast!

**Comment by Sikatsu** [comment]
This special flag is so we can find the cause of the issue better? I'll keep an eye out on the next version, hope we can get this one fixed soon.

**Comment by kangarko** [comment]
The special flag is in the code and won't show up anywhere. It's invisible and attached to players. This is used to prevent clashes when PMs are sent simultaneously.

You will see the other message though.

**Comment by Sikatsu** [comment]
Wait - not sure if I understand, that means if they sent a PM at the same time it no longer works? Or what does it do exactly?

**Comment by kangarko** [comment]
The flag will block sending PM to a player that's receiving another PM. Basically the entire handling of PM can take a few miliseconds and now during this time we simply block sending another PM to prevent /reply corruption — at least I hope it will fix this since I was not able to reproduce still.

**Comment by Sikatsu** [comment]
Will the player be notified if their PM was not sent in that case?

**Comment by kangarko** [comment]
Yes of course. So far they are hardcoded like "Another PM from you is being sent, wait a moment please..." or "{0} is currently receiving another PM, please wait..." but from the next version they will be translateable.

**Comment by kangarko** [comment]
Okay guys I so made some more code adjustments, moved the "reply player" update code to the top and removed saving it to data.db and database so it's much faster. 

Still was not able to and never could reproduce, sadly. But I ask you to test the next release and let me know if it did help! @Sikatsu  @aerulion @TheoRetisch1 thanks so much! :)

<img width="1537" alt="Screenshot 2020-12-24 at 07 48 12" src="https://user-images.githubusercontent.com/1918426/103067982-6c6a3500-45bc-11eb-91fd-99c7b6a0905b.png">

Merry Christmas!

**Comment by ElBananaa** [comment]
The issue is still happening in the latest version.
See #369.

**Comment by TheoRetisch1** [comment]
I can only confirm this, we also have the problem with version 10.1.11. The error pattern has not changed according to my observation.
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742514/debug.zip)

**Comment by UserDerezzed** [comment]
Can confirm that this is still a bug. Running latest (10.1.11) on Paper 1.12 Bungeecord-linked servers.

**Comment by TheoRetisch1** [comment]
The problem has become worse, sometimes a player sends a message with `/tell <player name> <message>` to another player. The message arrives at the receiver, but the sender doesn't see the sent message.
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5742996/debug.zip)

**Comment by OfT3N** [comment]
Got this problem randomly not even on /m command
![image](https://user-images.githubusercontent.com/62369973/103157233-eae3f400-47c1-11eb-83dd-dd44e14a4296.png)
![image](https://user-images.githubusercontent.com/62369973/103157238-fb946a00-47c1-11eb-95e2-bfb81b705abf.png)

**Comment by kangarko** [comment]
Looking into it right now

**Comment by Sikatsu** [comment]
https://www.dropbox.com/s/d10xhx140qqn5d2/Minecraft_%201.16.4%20-%20Multiplayer%20%283rd-party%20Server%29%202020-12-26%2022-40-02.mp4?dl=0

Around 1:05, Meloentjeeee and ItsJeWolfWolfie's msg goes from my account.
Around 3:30, Sil sends message to me, but its displayed as being a message from me to me.

**Comment by ElBananaa** [comment]
The issue has been reported in a new thread.
See #397.

**Comment by Malachiel87** [comment]
If i am not wrong this issue existed also on chatcontrol pro, it was not supposed to be a full recode? (the red version)
example https://github.com/kangarko/ChatControl-Pro/issues/1575 - and this issue, plus i noticed similiar issue that existed on old pro popping right now

**Comment by Sikatsu** [comment]
It was fixed for me on chatcontrol pro eventually

**Comment by Malachiel87** [comment]
yeah it was fixed but it come it out again on red version

**Comment by TheoRetisch1** [comment]
To describe the problem clearly again: On version 10.1.11 the following problem occurs very often (with about every hundredth private message: /r + /tell + /msg): The receiver gets the message, not from the sender, but from himself. The sender doesn't see that the message was sent out and sends it again to the receiver. On the second try everything works normally: The sender sees the sent message, the receiver gets the sent message.

**Comment by ElBananaa** [comment]
Hey guys!

Apologies for the issue.

> If i am not wrong this issue existed also on chatcontrol pro, it was not supposed to be a full recode? (the red version)
> example [kangarko/ChatControl-Pro#1575](https://github.com/kangarko/ChatControl-Pro/issues/1575) - and this issue, plus i noticed similiar issue that existed on old pro popping right now

Yes, ChatControlRed is a complete recode of ChatControlPro. However, (I guess) some libraries/methods used are still the same.
Anyways, don't worry, as Kangarko said above, he's aware of this issue, and he knows that this is pretty annoying for you guys, so he is actively working on fixing this issue.

Have a nice day! :)

**Comment by kangarko** [comment]
Happy Mondays, everyone loves Mondays... So I pushed a new version which has a completely rewritten private message handling system.

Previously we would do an async lookup for the player cache, so that we'd connect to your MySQL to get player's data etc., then perform the message. Now, we simply use the stored version on your server instantly. I do hope that this solves the issue. For a whole month I wasn't able to reproduce but I researched the cause so please do let me know below if you still continue to experience it on the next version. Thanks so much.

**Comment by Malachiel87** [comment]
It spam this error  continuos
https://gist.github.com/Malachiel87/1e6c6389985ecee702d81d812898a0cf
Debug: [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5749073/debug.zip)
version 1.8.8

EDIT: after full network restart the error gone, but i noticed now all tell work as bungee messages, i don't want it....

**Comment by kangarko** [comment]
What do you mean? /tell works over BungeeCord network if you have Integration.BungeeCord.Enabled on true.

I am closing this since the primary goal of this issue has been resolved. Feel free to comment below and I'll return to it.
