### ISSUE TITLE
1.20.1: Format_Discord variables do not parse correctly on some messages

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#2469]
### "/version ChatControlRed" - plugin version

1.20.10b

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

I am using CHC with discordsrv integration. I have my Format_Discord setup as:   Format_Discord: '**{tagdiscord}{tag4} {player}**: {message}'

Occasionally in my discord chat {tagdiscord}{tag4} will show instead of the correct variable. This only happens occasionally and there are no errors in console when this happens. It seems there are no patterns to this and it seems to happen randomly and break on ordinary messages.

**Comment by kangarko** [comment]
Should be fixed in the next version.

**Comment by TZ122** [comment]
Hey, I'm still receiving this issue on the latest version. 

https://imgur.com/a/ngnA92O

**Comment by kangarko** [comment]
Is there any console error on Spigot when that happens?

**Comment by TZ122** [comment]
Nope, there are no errors when it happens.

**Comment by kangarko** [comment]
I looked into it, and it seems like PlaceholderAPI or whatever plugin you are using for that variable is sometimes not returning the value right. We always replace it and we made the code sync so it should no longer happen. Mind asking their devs one time?

**Comment by TZ122** [comment]
Both the variables are Chatcontrolred Java script variables using this wiki section https://github.com/kangarko/ChatControl-Red/wiki/JavaScript-Variables

Does this still involve placeholderapi? If so I will reach out to the developer. 

Thanks

**Comment by kangarko** [comment]
Can you please send /chc debug file and point out which variables, exactly? Thanks.

**Comment by TZ122** [comment]
Sent via email - the variables are the only two in the variables folder

Thanks very much for taking a look.

**Comment by kangarko** [comment]
Sorry for the delay - I was not able to pinpoint the issue but what I can do is log these messages into a debug file. How often does it happen?

**Comment by TZ122** [comment]
> Sorry for the delay - I was not able to pinpoint the issue but what I can do is log these messages into a debug file. How often does it happen?

https://imgur.com/a/fIzO3lv Here are some time stamps of when it occurs

**Comment by kangarko** [comment]
Mind setting your Debug key in settings.yml to [discord-variables] ? A new file will appear called discord-variables.log with debug logs for your convenience not to spam your console. Please send me it to me as soon as the bug re-appears. Sorry for the inconvenience, I am unable to join your server in real time so we'd have to run a few simple tests.

[ChatControl-Red-10.22.0.zip](https://github.com/kangarko/ChatControl-Red/files/13256975/ChatControl-Red-10.22.0.zip)

**Comment by TZ122** [comment]
> [discord-variables]

It occurred again and did not log it https://pastebin.com/161mZ6bY
Will it log Minecraft chat -> Discord Chat variables?

**Comment by kangarko** [comment]
Thanks, I need some more days to debug this

**Comment by kangarko** [comment]
Try the next version please whether it will happen with the same frequency.

**Comment by TZ122** [comment]
Haven't seen the issue occur since latest update. Thanks!
