### ISSUE TITLE
Error loading plugin BungeeControl

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2982]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

11.0.8-RC

### Optional: Error log

https://mclo.gs/RlX3tmk

### Steps to reproduce

Sorry, I don't know if it's the section to report bungeecontrolred errors, but I couldn't find the section.

I've only updated to the latest version

**Comment by kangarko** [comment]
Yes, this is the correct place. Try the next release of bungeecontrol I will put out tonight. If it will continue, please send me your entire startup log uploaded via pastebin.com below.

**Comment by Z3r0xh** [comment]
> Yes, this is the correct place. Try the next release of bungeecontrol I will put out tonight. If it will continue, please send me your entire startup log uploaded via pastebin.com below.

BungeeControl [4.1.0]

https://pastebin.com/KQc9t9y0

**Comment by kangarko** [comment]
I'm not sure if NullCordX is supported, please try on native Waterfall.

Also, please ZIP me your entire BungeeControl/ folder so I can try reproducing.

**Comment by Z3r0xh** [comment]
> I'm not sure if NullCordX is supported, please try on native Waterfall.
> 
> Also, please ZIP me your entire BungeeControl/ folder so I can try reproducing.

https://ufile.io/lnn5gjfb

nullcord is born from bungee, it should be possible in this case, right? In case you need something to make it work, you can let me know so I can talk to the devs

**Comment by kangarko** [comment]
Please confirm is it broken or works fine on BungeeCord/Waterfall?

**Comment by Z3r0xh** [comment]
Ok, it seems to work fine in bungeecord, could nullcord support be added? I'm already talking to the nullcord devs. In case you need anything for that, let me know.

> Please confirm is it broken or works fine on BungeeCord/Waterfall?

**Comment by Z3r0xh** [comment]
> Please confirm is it broken or works fine on BungeeCord/Waterfall?

I'm talking to the dev of nullcordx, he asks me if you can add more debugs to see why it doesn't detect the platform

**Comment by kangarko** [comment]
Ask him to grant me a developer license to NullCord on builtbybit, my nick is kangarko, and I will attempt to fix it.

**Comment by xism4** [comment]
> Ask him to grant me a developer license to NullCord on builtbybit, my nick is kangarko, and I will attempt to fix it.

Hi, I'm NullCordX dev, as far as I saw the plugin only works with BungeeCord and Waterfall but not with other proxies, I don't see any compatibility problem other than that, could the proxy be added as well, since it practically doesn't break anything from the original core.

**Comment by kangarko** [comment]
> > Ask him to grant me a developer license to NullCord on builtbybit, my nick is kangarko, and I will attempt to fix it.
> 
> Hi, I'm NullCordX dev, as far as I saw the plugin only works with BungeeCord and Waterfall but not with other proxies, I don't see any compatibility problem other than that, could the proxy be added as well, since it practically doesn't break anything from the original core.

Thanks, this will be resolved within 48 hours on my end.

**Comment by kangarko** [comment]
Fixed. A new release will appear tonight.

**Comment by xism4** [comment]
> Fixed. A new release will appear tonight.

Thanks! You can contact me via discord if some other compatibility issue ocurrs

**Comment by Z3r0xh** [comment]
> Fixed. A new release will appear tonight.

It seems that it still doesn't load properly

https://mclo.gs/RWgWs0K

**Comment by kangarko** [comment]
@xism4 can you please add kangarko a licence for your fork on builtbybit.com for a temporary test? I cant fix it be heuristics. You can remove the license after the fix. Thanks.

**Comment by kangarko** [comment]
Update: Got it working. Tested standard boot. @Z3r0xh please wait until the next version and report if you experience any further issues. I apology for the delay.

**Comment by xism4** [comment]
> heuristics

This still beeing needed?

**Comment by kangarko** [comment]
Nope, all resolved.

**Comment by ImZowi** [comment]
I'm getting this error in v4.1.6:

```
[04:51:58 WARN]: Exception encountered when loading plugin: BungeeControl
java.lang.LinkageError: loader constraint violation: loader net.md_5.bungee.api.plugin.PluginClassloader @3f2169e9 wants to load interface net.kyori.adventure.text.Component. A different interface with the same name was previously loaded by net.md_5.bungee.api.plugin.PluginClassloader @541897c6. (net.kyori.adventure.text.Component is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @541897c6, parent loader 'app')
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:129) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:61) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:56) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:129) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:61) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:56) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:129) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:61) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:56) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.kyori.adventure.translation.GlobalTranslatorImpl.<init>(GlobalTranslatorImpl.java:45) ~[?:?]
        at net.kyori.adventure.translation.GlobalTranslatorImpl.<clinit>(GlobalTranslatorImpl.java:44) ~[?:?]
        at net.kyori.adventure.translation.GlobalTranslator.renderer(GlobalTranslator.java:75) ~[?:?]
        at net.kyori.adventure.platform.bungeecord.BungeeAudiencesImpl$Builder.<init>(BungeeAudiencesImpl.java:140) ~[?:?]
        at net.kyori.adventure.platform.bungeecord.BungeeAudiencesImpl.builder(BungeeAudiencesImpl.java:80) ~[?:?]
        at net.kyori.adventure.platform.bungeecord.BungeeAudiencesImpl.instanceFor(BungeeAudiencesImpl.java:76) ~[?:?]
        at net.kyori.adventure.platform.bungeecord.BungeeAudiences.create(BungeeAudiences.java:50) ~[?:?]
        at org.mineacademy.chatcontrol.bungee.lib.fo.platform.BungeePlatform.createAudiences(BungeePlatform.java:56) ~[?:?]
        at org.mineacademy.chatcontrol.bungee.lib.fo.platform.BungeePlugin.onEnable(BungeePlugin.java:166) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:282) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:270) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:60) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:12) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
        at de.brownie.nativeutil.Bootstrap.main(Unknown Source) ~[bungeecord.jar:1.21-R0.1-SNAPSHOT]
```

**Comment by kangarko** [comment]
@xism4 are you shading net.kyori.adventure directly into nullcordx?

@ImZowi can you confirm the latest version loads fine on native bungeecord or waterfall? does for me

**Comment by xism4** [comment]
> [@xism4](https://github.com/xism4) are you shading net.kyori.adventure directly into nullcordx?

Yep

**Comment by kangarko** [comment]
@xism4 yep then I'd definitely need access to test it, no idea why it's still not working but we should avoid downloading Adventure if it already exists. I can try reproducing but I can't guarantee to make it work unfortunately

**Comment by xism4** [comment]
> [@xism4](https://github.com/xism4) yep then I'd definitely need access to test it, no idea why it's still not working but we should avoid downloading Adventure if it already exists. I can try reproducing but I can't guarantee to make it work unfortunately

If you could enter my discord or contact me privately, I can provide you with a copy and a license for you to try it, in case you can't I will fix it.

**Comment by kangarko** [comment]
@xism4 nvm, I bought it

Works fine. There is a warning but it will load anyways:

![a](https://i.imgur.com/avkbspG.png) 

@ImZowi the latest version works

**Comment by xism4** [comment]
> [@xism4](https://github.com/xism4) nvm, I bought it
> 
> Works fine. There is a warning but it will load anyways:
> 
> ![a](https://camo.githubusercontent.com/88bca5fd30c783b73ea917571e640f7067e5935d6d0c93135dcbb0fe2204e026/68747470733a2f2f692e696d6775722e636f6d2f61766b627370472e706e67)
> 
> [@ImZowi](https://github.com/ImZowi) the latest version works

That's because it checks the version of the plugin and it just warns the user rigth?

**Comment by kangarko** [comment]
Yes it's just a warning because nullcord uses an unknown version string, feel free to ignore.
