### ISSUE TITLE
Changing usernames breaks the plugin for that player

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#309]
I'm sorry but closing my ticket was stupid, I am extremely busy irl and don't spend my time on github. There is no way to reproduce the issue except changing your username. Just change your username and see how it breaks, it's on bungeecord 1.16.4 latest version. https://i.imgur.com/raw9pCx.png
I do /msg JingleLizi hi and it still assumes it's her old username Liizii

Rebooting the server seems to do nothing to help

**Comment by ElBananaa** [comment]
Hey! Make sure you are using CHC Red v10.1.9, there's a fix related to nicks with this version.

**Comment by DoogiePC** [comment]
> Hey! Make sure you are using CHC Red v10.1.9, there's a fix related to nicks with this version.

But I didn't say nicks, I said usernames.

**Comment by ElBananaa** [comment]
Sorry, I thought you meant "nicks" by "username". So the player changed their username via Mojang website right?

**Comment by DoogiePC** [comment]
> Sorry, I thought you meant "nicks" by "username". So the player changed their username via Mojang website right?

That is correct, and I really need a fix because a staff member is literally fucked. They cannot do anything because ChatControl is just broken for them

**Comment by ElBananaa** [comment]
> > Sorry, I thought you meant "nicks" by "username". So the player changed their username via Mojang website right?
> 
> That is correct, and I really need a fix because a staff member is literally fucked. They cannot do anything because ChatControl is just broken for them

That's weird, it looks like you're the only one having this issue. Could you run `/chc debug` and upload the zip file generated here please?

**Comment by DoogiePC** [comment]
https://drive.google.com/file/d/1a-Ob5neNqCl0ujcpuzY4rCUyHTTK3z5n/view?usp=sharing

**Comment by kangarko** [comment]
Thanks, that should be solved. They may need to set their nick again though.

**Comment by DoogiePC** [comment]
> Thanks, that should be solved. They may need to set their nick again though.

It's not nicknames we've said already, it's Minecraft usernames.

**Comment by kangarko** [comment]
Yes. We've fixed it so that when user changes their Mojang username, it will work. If they had a custom ChatControl nickname set, however, they may be require to set it again.

**Comment by ElBananaa** [comment]
I reopened this issue since it's still happening apparently. I asked the author to provide an updated debug file asap with a new error.log.

**Comment by DoogiePC** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5743649/debug.zip)

**Comment by kangarko** [comment]
Can you please also state what username has changed from what to what?

**Comment by ElBananaa** [comment]
> Can you please also state what username has changed from what to what?

The player username was changed from `_the_cocos` to `the_cocos`.
The username in the usermap is the new one, but the database isn't updated.
He also tried to manually update the database with the new username, but as soon as the user logged back in, his username was changed to the old one in the database.

**Comment by Managering** [comment]
We've ran into the exact same issue. Player changed their name, can no longer be messaged etc.

**Comment by ElBananaa** [comment]
> We've ran into the exact same issue. Player changed their name, can no longer be messaged etc.

Hey!

Thanks for reporting the issues, apologies for the inconvenient.

Kangarko is aware of this issue and is probably already working actively on fixing it!
We'll let you know once this issue is fixed.

Have a nice day!

**Comment by DoogiePC** [comment]
> Can you please also state what username has changed from what to what?

_the_cocos -> the_cocos

**Comment by kangarko** [comment]
Sorry for waiting, I've changed the code and the problem seems now to be resolved. Please watch this, wait for the next version, and let me know if the next version will still have this issue, it was fixed on my end: https://www.loom.com/share/29e1b9f1a720433c80367b4229b33254

**Comment by DoogiePC** [comment]
![image](https://user-images.githubusercontent.com/29175381/103431028-100da380-4bc2-11eb-80ef-8765e281b470.png)
chatcontrol doesn't recognise the player "sanrioq" after they changed their username from "LilRanch_"
i do /ch join global write sanrioq and it says "oldname isn't connected through the bungeecord"

**Comment by ElBananaa** [comment]
> ![image](https://user-images.githubusercontent.com/29175381/103431028-100da380-4bc2-11eb-80ef-8765e281b470.png)
> chatcontrol doesn't recognise the player "sanrioq" after they changed their username from "LilRanch_"
> i do /ch join global write sanrioq and it says "oldname isn't connected through the bungeecord"

Hey!
Happy new year!

Make sure all your plugins/dependencies/server softwares are up-to-date.
Please send us the new `/chc debug` file.
Also take a look at your databse, and make sure that the player name was correctly updated in the database.

**Comment by kangarko** [comment]
Can you please check the MySQL database to see if the player's name has been updated as ElBananaa has suggested?

**Comment by DoogiePC** [comment]
-_-
This stuff is really hard to track, I have to rely on someone changing their username and then being online to grab it. It's really not easy to do, can you not just debug it yourself or check the code.

**Comment by kangarko** [comment]
You don't have to ask players to change their name, just look up sanrioq in the database and tell me whether the database still shows this as his old name LilRanch_

**Comment by kangarko** [comment]
May as well be that this bug is auto-fixed after the whole network is restarted. I will look into it

**Comment by DoogiePC** [comment]
I looked up both usernames in the database, no result. So I then tried looking up the UUID and nothing, it's gone?

**Comment by DoogiePC** [comment]
![image](https://user-images.githubusercontent.com/29175381/103680471-1fa03a00-4f7e-11eb-88dc-7307d0ed9126.png)

Still hasn't updated :/

**Comment by kangarko** [comment]
Okay I did make the database update when the player joins the game with a new name, but his UUID remains. If this won't help then unfortunately I have to put this on the backburner due to other more important priorities, but I hope it'll :)

**Comment by DoogiePC** [comment]
This is still not fixed @kangarko 
![2021-02-12_19 46 07](https://user-images.githubusercontent.com/29175381/107815344-2b480300-6d6b-11eb-9c0c-efde3c13d519.png)
"JingleLizi" changed their name to "LiziWizzy" and it's not updated.

**Comment by kangarko** [comment]
Was the player on the server while he changed his username? I am asking if he disconnected before changing?

**Comment by DoogiePC** [comment]
I really can't say, I did say relog and they rejoined and it was still broken.

**Comment by kangarko** [comment]
I am sorry, I don't know of any mechanism to get notified when a player changes his username while being online...

That being said, I forced some methods to use UUIDs instead of names. The only time you could encounter this again is when using /tell {name} where the name must be a name and we cannot use UUID lookups

**Comment by ElBananaa** [comment]
Hey!
Are you using ChatControlRed with BungeeCord? Or are you using it on a single server?

**Comment by DoogiePC** [comment]
Bungeecord

**Comment by kangarko** [comment]
I've changed BungeeCord synchronization system in attempt to solve some players not being reachable on the network after they change their Mojang username.

From my testing that works fine running cracked, let me know if anything comes up in the next version but I believe we' re on track getting this solved finally. Thanks for all the patience.

**Comment by kangarko** [comment]
Just comment below and I will see it.

**Comment by Revanrose6** [comment]
So I am still experiencing the same problem with the same player referenced here: https://github.com/kangarko/ChatControl-Red/issues/817#issuecomment-810070752

I checked the Database itself and it had written 3 different UUIDs for them. I deleted the entries and then it wrote 2 different UUIDs for him when he logged back and the problem persisted. It is no longer giving the 'not connected to database' error but he is incapable of switching channels.

1 of the UUIDs is a fake UUID and the other one listed is the correct one.

**Comment by ElBananaa** [comment]
> So I am still experiencing the same problem with the same player referenced here: [#817 (comment)](https://github.com/kangarko/ChatControl-Red/issues/817#issuecomment-810070752)
> 
> I checked the Database itself and it had written 3 different UUIDs for them. I deleted the entries and then it wrote 2 different UUIDs for him when he logged back and the problem persisted. It is no longer giving the 'not connected to database' error but he is incapable of switching channels.
> 
> 1 of the UUIDs is a fake UUID and the other one listed is the correct one.

Hey! Thanks for giving an update.
I'm sorry for the inconvenience.
Did you update the plugin to the latest version?

Unfortunately, I won't be able to provide you any support regarding this, but Kangarko will probably have a look at it monday.

**Comment by Revanrose6** [comment]
> > So I am still experiencing the same problem with the same player referenced here: [#817 (comment)](https://github.com/kangarko/ChatControl-Red/issues/817#issuecomment-810070752)
> > I checked the Database itself and it had written 3 different UUIDs for them. I deleted the entries and then it wrote 2 different UUIDs for him when he logged back and the problem persisted. It is no longer giving the 'not connected to database' error but he is incapable of switching channels.
> > 1 of the UUIDs is a fake UUID and the other one listed is the correct one.
> 
> Hey! Thanks for giving an update.
> I'm sorry for the inconvenience.
> Did you update the plugin to the latest version?
> 
> Unfortunately, I won't be able to provide you any support regarding this, but Kangarko will probably have a look at it monday.

I'm on 10.3.4 here's my debug log from /chc debug. 

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6289009/debug.zip)

**Comment by kangarko** [comment]
Can you please screenshot those database entries? Also are you running cracked or premium?

**Comment by Revanrose6** [comment]
I'm running a Premium Bungee, well Waterfall, Server. I will
<img width="1680" alt="Screen Shot 2021-04-12 at 10 27 39 AM" src="https://user-images.githubusercontent.com/6682989/114436045-c0078b00-9b79-11eb-8728-858119a7c0aa.png">

Screen shot ^ is a little weird looking so I also copied it here:

+--------------------------------------+--------------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| UUID                                 | Name         | Nick | Data                                                                                                                                                                                    | LastModified  |
+--------------------------------------+--------------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| d9b1ae00-8bfd-4760-a664-474eaa8377de | pauldersgate | NULL | {"Channels":{"staff":"read","local":"read","nation":"read","trade":"read","itrade":"read","auction":"read","global":"write","advertisements":"read","supporter":"read","alert":"read"}} | 1618176984892 |
| ffb24bf2-574e-31ba-87e2-b9a9f33b58dd | pauldersgate | NULL | {"Channels":{"local":"read","nation":"read","trade":"read","itrade":"read","auction":"read","global":"write","staff":"read"}}                                                           | 1618156641791 |
+--------------------------------------+--------------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+

**Comment by Revanrose6** [comment]
For reference. This is what the database says when I pull up mine.

<img width="1677" alt="Screen Shot 2021-04-12 at 10 32 27 AM" src="https://user-images.githubusercontent.com/6682989/114436617-66539080-9b7a-11eb-891d-b34279aa2768.png">

| UUID                                 | Name       | Nick                  | Data                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | LastModified  |
+--------------------------------------+------------+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| bc2b57bb-02db-4023-8841-5518d118ff64 | revanrose6 | §4Rev§can§7ro§fse     | {"Left_Channels":["Staff"],"Channels":{"trade":"read","auction":"read","advertisements":"read","supporter":"read","itrade":"read","developer":"read","alert":"read","nation":"read","admin":"read","staff":"read","local":"write","global":"read"},"Spying_Sectors":["sign","private_message","chat","anvil","mail","book","command"],"Spying_Channels":["Nation","Auction","Staff","Developer","Local","Admin","Advertisements","Global","Trade","Alert","ITrade","Supporter"]} | 1618248213831 |

**Comment by kangarko** [comment]
I've added an option to use names instead of UUIDs to lookup them from MySQL, set the option to false. This will still cause players to lose their saved channels or ignored players when they change their mojang username but will prevent database duplicate entries and potentially greater issues.

<img width="761" alt="Screenshot 2021-04-13 at 17 16 46" src="https://user-images.githubusercontent.com/1918426/114577117-0a713080-9c7c-11eb-93b7-be704875ec62.png">
