### ISSUE TITLE
VelocityControl 2.2.5 Not Working

### ISSUE THREAD

**Issue by ArifErdoganK** [kangarko/ChatControl#3091]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

ChatControl 11.2.5 VelocityControl 2.2.5

### Optional: Error log

Nothing error

### Steps to reproduce

Due to migrating to ChatControl v11.2.5, I purchased VelocityControl v2.2.5, but despite repeatedly checking the instructions at https://github.com/kangarko/ChatControl/wiki/proxy, messages still don't get sent to other servers. This issue did not exist in VelocityControl-3.11.7-SNAPSHOT.

Velocity **ChatControl settings.yml:**
```
Server_Aliases:
  faction-klan: Merkez
  faction-arsa: Arsa
  faction-arsa2: Arsa2
  faction-arena: Arena
  faction-boss: Boss
  faction-hammadde: Hammadde
  faction-event: Event
  faction-duello: Duello
```

**Velocity.toml:**
```
[servers]
    "faction-arena" = ""
    "faction-duello" = ""
    "faction-arsa" = ""
    "faction-hammadde" = ""
    "faction-event" = ""
    "faction-arsa2" = ""
    "faction-boss" = ""
    "faction-klan" = ""
    "faction-build" = ""
```

Bukkit **ChatControl settings.yml:**
```
  List:
    standard:
      Format: chat
      Format_Spy: '@noprefix chat'
      Format_Console: '[Klan] {pl_prefix}{player}&8: &f{message}'
      Proxy: true
```

Bukkit **ChatControl proxy.yml:**
```
Enabled: true
Prefix: "<dark_gray>[<yellow>{server_name}<dark_gray>] <gray>"
Server_Name: 'faction-klan'
```

**Comment by kangarko** [comment]
Should be resolved tonight.

**Comment by ArifErdoganK** [comment]
> Should be resolved tonight.

I applied the latest updates to the Velocity and Bukkit servers, but nothing changed. I updated the - character in the server names to _, but the issue still wasn't resolved.

**Comment by kangarko** [comment]
Can you set Debug key to [proxy] in both ChatControl and VelocityControl please and let me know the outputs?

Also, just to confirm you are not running Redis?

**Comment by Nyxari** [comment]
I'm having this same issue, I keep getting the "enable MySQL in settings.yml" but i dont see any setting whatsoever in Chatcontrol>settings.yml to enable MySQL its just able to debug it... 

https://ufile.io/bn1hcl7g 
here is the debug file

**Comment by ArifErdoganK** [comment]
> Can you set Debug key to [proxy] in both ChatControl and VelocityControl please and let me know the outputs?
> 
> Also, just to confirm you are not running Redis?

[13:36:22] [Async Chat Thread - #0/INFO]: [Klan] {pl_prefix}ArifErdoganK: s
[13:36:22] [Craft Scheduler Thread - 11/INFO]: [ChatControl] Note: Not sending ArifErdoganK's chat to spying players because he has 'chatcontrol.bypass.spy.chat' permission. Player messages with such permission are not spied on. To disable that, negate this permission (a false value if using LuckPerms). This message only shows once per 3 hours.
[13:36:22] [Craft Scheduler Thread - 11/INFO]: [ChatControl] Note: Not logging ArifErdoganK's chat because he has 'chatcontrol.bypass.log' permission. Players with these permission do not get their content logged. To disable that, negate this permission (a false value if using LuckPerms). This message only shows once per 3 hours.
[13:36:22] [Netty Server IO #1/ERROR]: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.ShadowColor net.kyori.adventure.text.format.Style.shadowColor()'
[13:36:22] [Server thread/INFO]: ArifErdoganK lost connection: Disconnected

![Image](https://github.com/user-attachments/assets/f9fd2955-930f-4007-b067-741b7dd17059)


When I try to get a debug, I also crash.
[13:38:18] [Server thread/INFO]: ArifErdoganK issued server command: /chatcs debug
[13:38:18] [Netty Server IO #0/ERROR]: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.ShadowColor net.kyori.adventure.text.format.Style.shadowColor()'
[13:38:18] [Server thread/INFO]: ArifErdoganK lost connection: Disconnected


ChatControl-11.2.6
VelocityControl-2.2.6

**Comment by kangarko** [comment]
> I'm having this same issue, I keep getting the "enable MySQL in settings.yml" but i dont see any setting whatsoever in Chatcontrol>settings.yml to enable MySQL its just able to debug it...
> 
> https://ufile.io/bn1hcl7g here is the debug file

Sorry about that, the message was outdated. I will update it. You should enable the database in database.yml now, setting the Type key from local to remote.

If still having issues please open a new ticket.

**Comment by kangarko** [comment]
> > Can you set Debug key to [proxy] in both ChatControl and VelocityControl please and let me know the outputs?
> > Also, just to confirm you are not running Redis?
> 
> [13:36:22] [Async Chat Thread - #0/INFO]: [Klan] {pl_prefix}ArifErdoganK: s [13:36:22] [Craft Scheduler Thread - 11/INFO]: [ChatControl] Note: Not sending ArifErdoganK's chat to spying players because he has 'chatcontrol.bypass.spy.chat' permission. Player messages with such permission are not spied on. To disable that, negate this permission (a false value if using LuckPerms). This message only shows once per 3 hours. [13:36:22] [Craft Scheduler Thread - 11/INFO]: [ChatControl] Note: Not logging ArifErdoganK's chat because he has 'chatcontrol.bypass.log' permission. Players with these permission do not get their content logged. To disable that, negate this permission (a false value if using LuckPerms). This message only shows once per 3 hours. [13:36:22] [Netty Server IO [#1](https://github.com/kangarko/ChatControl/issues/1)/ERROR]: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.ShadowColor net.kyori.adventure.text.format.Style.shadowColor()' [13:36:22] [Server thread/INFO]: ArifErdoganK lost connection: Disconnected
> 
> ![Image](https://github.com/user-attachments/assets/f9fd2955-930f-4007-b067-741b7dd17059)
> 
> When I try to get a debug, I also crash. [13:38:18] [Server thread/INFO]: ArifErdoganK issued server command: /chatcs debug [13:38:18] [Netty Server IO #0/ERROR]: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.ShadowColor net.kyori.adventure.text.format.Style.shadowColor()' [13:38:18] [Server thread/INFO]: ArifErdoganK lost connection: Disconnected
> 
> ChatControl-11.2.6 VelocityControl-2.2.6

Please post me your /chc debug

**Comment by ArifErdoganK** [comment]
> > > Can you set Debug key to [proxy] in both ChatControl and VelocityControl please and let me know the outputs?
> > > Also, just to confirm you are not running Redis?
> > 
> > 
> > [13:36:22] [Async Chat Thread - #0/INFO]: [Klan] {pl_prefix}ArifErdoganK: s [13:36:22] [Craft Scheduler Thread - 11/INFO]: [ChatControl] Note: Not sending ArifErdoganK's chat to spying players because he has 'chatcontrol.bypass.spy.chat' permission. Player messages with such permission are not spied on. To disable that, negate this permission (a false value if using LuckPerms). This message only shows once per 3 hours. [13:36:22] [Craft Scheduler Thread - 11/INFO]: [ChatControl] Note: Not logging ArifErdoganK's chat because he has 'chatcontrol.bypass.log' permission. Players with these permission do not get their content logged. To disable that, negate this permission (a false value if using LuckPerms). This message only shows once per 3 hours. [13:36:22] [Netty Server IO [#1](https://github.com/kangarko/ChatControl/issues/1)/ERROR]: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.ShadowColor net.kyori.adventure.text.format.Style.shadowColor()' [13:36:22] [Server thread/INFO]: ArifErdoganK lost connection: Disconnected
> > ![Image](https://github.com/user-attachments/assets/f9fd2955-930f-4007-b067-741b7dd17059)
> > When I try to get a debug, I also crash. [13:38:18] [Server thread/INFO]: ArifErdoganK issued server command: /chatcs debug [13:38:18] [Netty Server IO #0/ERROR]: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.ShadowColor net.kyori.adventure.text.format.Style.shadowColor()' [13:38:18] [Server thread/INFO]: ArifErdoganK lost connection: Disconnected
> > ChatControl-11.2.6 VelocityControl-2.2.6
> 
> Please post me your /chc debug

When I try to get a debug, I also crash.
[13:38:18] [Server thread/INFO]: ArifErdoganK issued server command: /chatcs debug
[13:38:18] [Netty Server IO #0/ERROR]: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.ShadowColor net.kyori.adventure.text.format.Style.shadowColor()'
[13:38:18] [Server thread/INFO]: ArifErdoganK lost connection: Disconnected

**Comment by kangarko** [comment]
What is your server version? Please send me /version then

**Comment by ArifErdoganK** [comment]
> What is your server version? Please send me /version then

> version
[12:32:27 INFO]: This server is running PandaSpigot version git-PandaSpigot-158 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (Git: 2642118)
[12:32:27 INFO]: Checking version, please wait...
[12:32:28 INFO]: You are running the latest version

**Comment by kangarko** [comment]
The authors of the old fork need to update their Adventure API or delete it from the jar.

**Comment by PurplesInc** [comment]
As one of the students of MineAcademy and a contributor to PandaSpigot, I assure you that this will be fixed in a few minutes.

**Comment by kangarko** [comment]
That is great thank you so much! I believe the issue started to occur now that we updated Adventure version. I use a library loader called "libby", which loads it in the common classloader shared with Bukkit, which results in Jar Hell and Java seems to prioritize the older version resulting in this error.

So the easiest is just to bump your Adventure version. The hardest solution would be to rewrite [libby](https://github.com/AlessioDP/libby).

**Comment by ArifErdoganK** [comment]
> That is great thank you so much! I believe the issue started to occur now that we updated Adventure version. I use a library loader called "libby", which loads it in the common classloader shared with Bukkit, which results in Jar Hell and Java seems to prioritize the older version resulting in this error.
> 
> So the easiest is just to bump your Adventure version. The hardest solution would be to rewrite [libby](https://github.com/AlessioDP/libby).

Can you check this?

Link: https://github.com/hpfxd/PandaSpigot/pull/300

**Comment by kangarko** [comment]
Yes but I have no idea how it works internally, all I know is that we updated Adventure library dependency and since then you reported it broken
