### ISSUE TITLE
Paper/Velocity 1.21.5: Unclickable links

### ISSUE THREAD

**Issue by Hazbo56** [kangarko/ChatControl#3142]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

11.3.1

### ZIP of "/chc debug"

Sent email with ufile link.

### Steps to reproduce

Upgrade to 1.21.5, links that were otherwise clickable through ChatControl and other plugins are now no longer clickable. Downgrading allows them to be clickable again.

I've seen some others have the same issue but no bug reports posted, though I'm assuming it's not a settings issue, as I was able to do the same I have clickable links enabled in my config.

**Comment by kangarko** [comment]
Thanks, investigating asap in 24h or less.

**Comment by kangarko** [comment]
Should be solved in the next version.

**Comment by kangarko** [comment]
Unfortunately wont be completely solved until Adventure fixes it, see https://github.com/PaperMC/Velocity/issues/1553 and https://github.com/KyoriPowered/adventure/issues/1194

**Comment by StKillReal** [comment]
It still doesn't work with 11.3.3 and the latest Velocity build. At least not with the vanilla /tellraw command, WorldGuard plugin chat buttons, or the PlasmoVoice groups addon. I'm sure the list of features with unclickable links is much longer

**Comment by kangarko** [comment]
Can you provide an example of your chatcontrol config the part that doesnt work?

Also note your other plugins need to update their Adventure version for them to work...

**Comment by StKillReal** [comment]
So, for example - `tellraw @a ["Press ",{"text":"here","clickEvent":{"action":"open_url","value":"https://www.google.com/"},"hoverEvent":{"action":"show_text","contents":"Open in browser"},"color":"gold"}," to open website"]` isn't clickable. I didn't even touch the config since updating to 1.21.5 from 1.21.4 and clickable links are enabled

![Image](https://github.com/user-attachments/assets/74ca6374-a406-4d69-9111-793383754631)

**Comment by kangarko** [comment]
Yeah because 1.21.5 changed the json syntax, thats something we dont control. The new syntax is `/tellraw @a { "text": "Hello world", "click_event": { "action": "open_url", "url": "https://google.com" } }`

See https://misode.github.io/text-component/ for help.
