### ISSUE TITLE
Purpur 1.21.5: Factions Relational placeholder wierd behaviour

### ISSUE THREAD

**Issue by goldenartur** [kangarko/ChatControl#3172]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

11.3.5

### ZIP of "/chc debug"

https://ufile.io/ksl59dqr

### Steps to reproduce

factions relational placeholder {rel_factionsuuid_relation_color} outputs the color but also  adds "color" text and the color doesnt continue after the color text, the color the was before continues.

  prefix:
    Message: '{luckperms_prefix}<yellow>TEST</yellow> '
    Hover:
    - '&r{luckperms_meta_prefix_legacy} {player_name}'
    - ''
    - ':click_action_left: &8> <#9ECCA4>Vajuta poe avamiseks.'
  factionsprefix:
    Message: '{rel_factionsuuid_relation_color}TEST{factionsuuid_player_role}'
    Sender_Condition: '''%factionsuuid_player_role_name%'' != ''None'' && {sender_is_player}'

![Image](https://github.com/user-attachments/assets/6616494c-66d2-47b8-85ff-464636201ff0)

It should output just the color which in my example should be &a and make the icon/text i have after "color" green but it creates color text which is only green and nothing else.

**Comment by MotikaCraft-TheJoshua** [comment]
I confirm this happening too, in my case i tested on softwares:
- Paper 1.8.8
- Carbon (paid fork) 1.8.8

Same CHC version as OP

Test:
![Image](https://github.com/user-attachments/assets/35268653-057a-4284-90e1-91ac65bfa589)

config part:
```
Message: 'e {rel_factionsuuid_relation_color} e {factionsuuid_faction_name}'
```

**Comment by kangarko** [comment]
Hey hey, apologizes for the big delay, I am gonna be getting present with this together with my new colleague @devpedrobarbosa within 24 hours.

**Comment by MotikaCraft-TheJoshua** [comment]
@goldenartur @kangarko this issue should be renamed to generalize issue with relational placeholders, because this issue happens with any relational placeholders being used in chc, not only factions one

**Comment by kangarko** [comment]
Thanks guys and apologize for the wait, I fixed it. Closing!

**Comment by MotikaCraft-TheJoshua** [comment]
> Thanks guys and apologize for the wait, I fixed it. Closing!

Hello, thanks
However i see this happening now, something broke

before updating to commit `ed71d79` (this is version release BBB 11.3.5):
![Image](https://github.com/user-attachments/assets/4bf9b33f-7823-487c-9f94-d4f3c4e90b3b)

after updating to commit `ed71d79`:
![Image](https://github.com/user-attachments/assets/95bfc770-870d-4e13-acbe-c47840affef8)

**Comment by MotikaCraft-TheJoshua** [comment]
I don't want to be bothering or something, i just want to say that it's ok to wait, but would be cool if somehow you missed the notification, to be able to trigger something just to remind you, talking for example about this. As i said, nobody is in a hurry but it's cool to just remind for safety if notification has not been seen or whatever

![Image](https://github.com/user-attachments/assets/d9b3d917-f31d-4328-877e-51ed8566c0fa)

Thanks

**Comment by kangarko** [comment]
Hey! We see all notifications. @devpedrobarbosa please check it out. Pedro did you get the notification too?

**Comment by MotikaCraft-TheJoshua** [comment]
Sorry to bother, any news?

**Comment by devpedrobarbosa** [comment]
Hey there!

Sorry for the delay.
I am currently working on trying to reproduce this issue.

It will be fixed as soon as possible.

Thanks.

**Comment by MotikaCraft-TheJoshua** [comment]
i will send you the format i am using, this is the only part i have on my server

```yml
  chat_message:
    Sender_Condition: '!{sender_is_discord}' # && "{luckperms_primary_group_name}" != "Admin"'
    Receiver_Condition: '"{parseother_{{sender_name}}_{player_has_permission_chat.tranquilized}}" == "no" || "{parseother_{{sender_name}}_{player_has_permission_chat.tranquil.exempt}}" == "yes" || "{player_name}" == "{sender_name}" || ("{player_has_permission_chat.tranquil.see}" == "yes" && "{parseother_{{sender_name}}_{player_has_permission_chat.tranquilized}}" == "no")'
    #Message: '{luckperms_meta_username_color}{player_chat_color}{player_chat_decoration}{message}'
    Message: '{luckperms_meta_chat_color}{luckperms_meta_chat_color_forced}{luckperms_meta_chat_format_forced}{message}'
```

this worked always, never broke, until this release to fix relational placeholder is pushed...

As soon as i remove Receiver_Condition, it works

i'll need to do debugging on this and will get asap to here

**Comment by MotikaCraft-TheJoshua** [comment]
Empty chat when i send messages with config i am sending below in this same github comment
![Image](https://github.com/user-attachments/assets/586495ae-65b6-4019-a8a7-5e0f0f6fdbc5)

```yml
  chat_message:
    Sender_Condition: '!{sender_is_discord}' # && "{luckperms_primary_group_name}" != "Admin"'
    Receiver_Condition: '"{player_name}" == "{sender_name}"'
    #Message: '{luckperms_meta_username_color}{player_chat_color}{player_chat_decoration}{message}'
    Message: '{luckperms_meta_chat_color}{luckperms_meta_chat_color_forced}{luckperms_meta_chat_format_forced}{message}'
```

Is Receiver_Condition broken? because if i remove Receiver_Condition and then i put {player_name} placeholder and {sender_name} placeholder directly into "Message: <here>", it properly shows sender's name, so it should work, because player name is correct to sender name, so i assume it's Receiver Condition that is broken?

**Comment by MotikaCraft-TheJoshua** [comment]
I think this debugging is enough but if there is anything i could else test but i minimalized distance from default config - let me know @devpedrobarbosa

**Comment by devpedrobarbosa** [comment]
Hey @MotikaCraft-TheJoshua,

The Pull Request above will most probably fix this issue.
I am still testing it, though. Another patch may be necessary in the future.

Once it's merged, let me know if you still face the same issues.

Thanks for waiting!

**Comment by MotikaCraft-TheJoshua** [comment]
> Hey [@MotikaCraft-TheJoshua](https://github.com/MotikaCraft-TheJoshua),
> 
> The Pull Request above will most probably fix this issue. I am still testing it, though. Another patch may be necessary in the future.
> 
> Once it's merged, let me know if you still face the same issues.
> 
> Thanks for waiting!

Hello,
i have compiled this version you referenced

I will first show screenshot of how format is
![Image](https://github.com/user-attachments/assets/f0e99638-6ed3-449d-a2d6-f67264e3133b)

Obviously, the formatting now is not broken in a way it doesn't work, but as you can see, it's still broken, but functional (but i hope it will be handled like before, because before you can mix legacy &4 &6 etc with <minimessage>, and it worked really great)

Now as you can see on screenshot
- i created 2 factions via 2 alt accounts
- i made faction relation enemy via /f enemy <faction_name>
- i sent messages via both accounts
- i took screenshot from one of the accounts (username: TheJoshua) so as you can see his own faction is displayed in proper coloring which is light green, whereas for enemy faction, it's displayed as red

Conclusion:
- relational colors are now good, except that everything else is broken in most of cases (even that X which is in default config is not properly displayed, you can see that <click> tag)

Also, i hope you'll reopen this issue as this is really not fixed and the title of this github issue is still very relevant issue.
Thank you so much for the effort!

**Comment by devpedrobarbosa** [comment]
Working on it right now.

Thanks for reaching back so quickly.

**Comment by MotikaCraft-TheJoshua** [comment]
@devpedrobarbosa please take a look at this

I am using ChatControl latest release from BuiltByBit for this purpose and this screenshot (11.3.5)
![Image](https://github.com/user-attachments/assets/23c342fe-fb9e-45ce-98bc-9f52f872cd80)

Now check this out

If i parse this placeholde,r relational one, which is from my custom papi expansion, it parses regularly, however, only when parsed in chatcontrol, it adds that "color" at the end, which also finishes the colorization (anything ater this is not colored, it's like it adds at the end "<whatever_relational_color_or_some_text>color&r" were of course &r is like <reset>, stops the colorization/formatting looks)

I hope this will help, because it would be so much better to try to fix this "color" thingy, maybe revert those changes in commit `ed71d79` about relational placeholders and simply fix this, because relational placeholders work correctly, as you can see on the screenshot above, exact same placeholder (custom one from my expansion, shown in chat) was used in chat formatting of CHC (showing that "Legend" prefix) differently for user `TheJoshua` and differently for `Test` user, so it seems like relational placeholders work just fine except that intercepting "color<reset>" or whatever there happens...

I am saying all this because i personally think that currently plugin works great and there is no need for such big refactor for this small thing, i am scared that legacy &4 &6 etc color formatting and minimessage one will be broken when used together, and for now it works absolutely great

PS. if it's not obvious - because players are enemy factions, that's why "color" is colored in red (&c) for enemy faction in chat, however, there goes that bug where that text "color" is spawned outta nowhere, and cancelling further colorization

Thank you for reading, hope this helps

**Comment by devpedrobarbosa** [comment]
Thanks for your effort on researching all this. It is being in fact helpful.
As far as I know, we're keeping support for both legacy colors (&a) and mini tags (<green>).

Actually, I'm not being able to reproduce it.
Is your ChatControl folder exactly the way it was when you shared the ZIP of your `/chc debug`?
Because that is what I am using to try and reproduce it here.
If not, can you please share it again?

**Comment by devpedrobarbosa** [comment]
As you can see, I was able to mix everything inside one part:

```
  everything:
    Message: '&7[<gold>Channel&7] {rel_factionsuuid_relation_color}RelColor {player_nick} <italic>&7></italic> {message}'
```

![Image](https://github.com/user-attachments/assets/627dfa52-cc21-4557-b6b9-4436c6a5afc7)

What am I missing in order to reproduce it? Please let me know.

**Comment by MotikaCraft-TheJoshua** [comment]
![Image](https://github.com/user-attachments/assets/17e5dc2b-3018-4ecb-9ed2-ce361bcc29b7)

```yml
  everything:
    Message: '&7[<gold>Channel&7] {rel_factionsuuid_relation_color}RelColor&r {player_nick} <italic>&7></italic> {message}'
```

i added &r but i also tested with <reset>, you can see how it parses now

with your exact example it works like this:

![Image](https://github.com/user-attachments/assets/64c94d95-927d-4a80-8ba8-a4b48254c6d8)

As you can see, the > is not colored correctly, and i am using only this one part, nothing more or less than your example

**Comment by kangarko** [comment]
Should be fixed in the next release :)
