### ISSUE TITLE
Spigot 1.21.10: Could not pass Event InventoryCreativeEvent

### ISSUE THREAD

**Issue by Jerlag01** [kangarko/ChatControl#3342]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.5.5

### Optional: Error log

https://pastebin.com/YVFptkmH

### ZIP of "/chc debug"

[debug.zip](https://github.com/user-attachments/files/22993093/debug.zip)

### Steps to reproduce

1. install spigot 1.21.10
2. start the server
3. join and go in creative
4. interact with the inventory

**Comment by devpedrobarbosa** [comment]
Hey @Jerlag01 

Thanks for reaching out.

This error is most likely caused by incompatibility between latest version of ChatControl and latest version of Paper.

We are actively working on catching up with the most recent updates and this should be fixed upon the next release.

**Comment by devpedrobarbosa** [comment]
@Jerlag01 

Should be fixed in v11.5.6

**Comment by Jerlag01** [comment]
I'll test it later today

**Comment by Jerlag01** [comment]
@devpedrobarbosa The error still shows in the console.
Here is a link to the pastebin: https://pastebin.com/petmua8Z

**Comment by kangarko** [comment]
@devpedrobarbosa missed?

**Comment by devpedrobarbosa** [comment]
@kangarko 

Totally missed it, I'm sorry.

The issue was fixed in `v11.5.7`.

Hope @Jerlag01 got to test it and it worked well :)
