### ISSUE TITLE
Paper 1.21: Javascript custom variables Failing randomly

### ISSUE THREAD

**Issue by Hackerjef** [kangarko/ChatControl#3345]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

11.5.5

### Optional: Error log

No errors from error file/console that is directly resulted to the placeholders not working

### ZIP of "/chc debug"

Messaged directly to email for privacy - 
subject: "The Cavern | GH issue Variables missing"

### Steps to reproduce

1. Use JavaScript to make a custom variables
2. wait x min/hours for it to break randomly. 

##  Example: 

<img width="900" height="402" alt="Image" src="https://github.com/user-attachments/assets/11e55988-eff0-4243-8d2f-68c2c6fb4585" />

<img width="2551" height="384" alt="Image" src="https://github.com/user-attachments/assets/c9477a8d-5f70-4ae7-8807-b8d0b2be5a67" />

Both examples are of ch's built in ability to use variables with javascript output

**Comment by devpedrobarbosa** [comment]
Hey @Hackerjef 

Thanks for sharing. I'm sorry that this is happening.

Could you clarify to me if you use ChatControl and our JavaScript variables prior to the most recent updates? Has it ever happened before?

Thanks!

**Comment by Hackerjef** [comment]
hello @devpedrobarbosa 

So we are deploying chatcontrol on this version as we just recently switched over from a different chat plugin so this should be the only version we used other then the bug fix a few days ago, but it was happening prior to that

thanks for looking into this

> Hey @Hackerjef 
> 
> Thanks for sharing. I'm sorry that this is happening.
> 
> Could you clarify to me if you use ChatControl and our JavaScript variables prior to the most recent updates? Has it ever happened before?
> 
> Thanks!

**Comment by kangarko** [comment]
@Hackerjef first of all I am terribly sorry for the delays.

Is any error showing up in the console? How often it does happen? Any steps to reproduce or completely random? Player is on the same server or another under proxy?

**Comment by Hackerjef** [comment]
@kangarko Hello! It's all good, we removed a lot of the custom variables temp to allow for basic chat usage for the time being but we are still seeing internal variables having problems

### Errors:
We haven't seen any errors leading up to the variables disappearing/not working 

the only errors we have seen relating to chat control is one of the plugins that use papi don't allow for null players, while this was a error we where seeing on startup on the dev environment to prod, variables continued to work. (we disabled using those in chat control and the issues kept happening)

### Reproducing:
Ultimately is quite random, but it's always related to higher Uptime, in our dev environment we never caught this until we had it on prod for a few hours

### Player is on the same server or another under proxy?
All of our servers are under the proxy if that is what you are asking.

**Comment by devpedrobarbosa** [comment]
@Hackerjef 

Unfortunatelly I still was not able to reproduce this on my end.

We're investigating it and will keep you updated.

**Comment by Hackerjef** [comment]
Is there anything i can offer to help diagnose? im pretty open to suggestions to get this to work 

> @Hackerjef 
> 
> Unfortunatelly I still was not able to reproduce this on my end.
> 
> We're investigating it and will keep you updated.

**Comment by devpedrobarbosa** [comment]
@Hackerjef 

Unfortunatelly at this point it's just going through the code and trying to find something that could be breaking in this specific scenario. I don't think I'm going to be able to reproduce this on my PC to debug what's wrong. I've even left it on overnight and it worked pretty fine. (+/- 8hrs uptime but with only 2 accounts logged in).

I'll bring it up with @kangarko once again and hopefully we will identify this issue and provide a proper fix.

Thanks for understanding.

**Comment by kangarko** [comment]
Apologizes for the delay, turned out to be a bit more advanced issue. [Should be solved](https://github.com/kangarko/Foundation/commit/1bf3bd1a22aad2ddf2e8cab376964e16406d9901). Let us know if you will experience it again! Thanks.

**Comment by Hackerjef** [comment]
@kangarko @devpedrobarbosa Hey so we are still having the issue, we updated to the last version (11.5.9) I've generated another debug zip if wanted. we picked through our server log and haven't seen any stacktrace or any issue that we can see that's causing this directly. We removed any problematic placeholders prior to updating (placeholders not allowing null players ) to give it the best we can.


Now something my staff reported is our daily (12hr) restart 90% of the time restarts no problem, but on some cases like what we have currently chat control fails to register placeholders. but with no stacktrace to be seen.
<img width="985" height="252" alt="Image" src="https://github.com/user-attachments/assets/539e2d8f-2a2f-4122-ab9b-7cb30c8d66b3" />

<img width="1136" height="157" alt="Image" src="https://github.com/user-attachments/assets/62dd7784-b71b-4b3c-9182-e8c85f55ee72" />

**Comment by kangarko** [comment]
@devpedrobarbosa lets resolve on next tuesday call

**Comment by devpedrobarbosa** [comment]
@Hackerjef 

Please test `11.6.0` since the update we've mentioned has been released just now.

By the way I'm sorry for the late response, there was a major delay on my end.

Thanks for understanding.
