### ISSUE TITLE
Problem when someone speaks from Discord

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#3355]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

ChatControl version 11.5.9

### Optional: Error log

https://mclo.gs/lJNuLTj

### ZIP of "/chc debug"

https://ufile.io/dzj33atq

### Steps to reproduce

This error appears when a user speaks from Discord

**Comment by kangarko** [comment]
@devpedrobarbosa can you just add try-catch around the calling method and supress this error? unfortunately it's a network error nothing we can fix, we just need to handle this gracefully

**Comment by devpedrobarbosa** [comment]
@kangarko Sure!

**Comment by devpedrobarbosa** [comment]
@Z3r0xh 
You should not see this error again after upadting.

**Comment by Z3r0xh** [comment]
> @Z3r0xh 
> You should not see this error again after upadting.

NICE! Thanks for your time!

**Comment by Z3r0xh** [comment]
> [@Z3r0xh](https://github.com/Z3r0xh) You should not see this error again after upadting.

Is the release date of the update that fixes this problem known?

**Comment by kangarko** [comment]
@devpedrobarbosa

**Comment by devpedrobarbosa** [comment]
@Z3r0xh 

I'm sorry for the late response. There was a major delay on my end.

Update is out now.

Hope everything works out :)

**Comment by Z3r0xh** [comment]
> [@Z3r0xh](https://github.com/Z3r0xh)
> 
> I'm sorry for the late response. There was a major delay on my end.
> 
> Update is out now.
> 
> Hope everything works out :)

It's not fixed yet
https://mclo.gs/sEUJmKH

**Comment by kangarko** [comment]
@devpedrobarbosa

**Comment by devpedrobarbosa** [comment]
@Z3r0xh @kangarko 

This should be fixed in the latest version available.

**Comment by Z3r0xh** [comment]
> [@Z3r0xh](https://github.com/Z3r0xh) [@kangarko](https://github.com/kangarko)
> 
> This should be fixed in the latest version available.

not fixed yet

`[15:57:21 WARN]: Couldn't find profile with name: MrDonJared
com.mojang.authlib.exceptions.MinecraftClientHttpException: Couldn't find any profile with name mrdonjared
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:103) ~[authlib-7.0.61.jar:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:56) ~[authlib-7.0.61.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfileByName(YggdrasilGameProfileRepository.java:117) ~[universe-1.21.10.jar:?]
        at com.destroystokyo.paper.profile.PaperGameProfileRepository.findProfileByName(PaperGameProfileRepository.java:49) ~[universe-1.21.10.jar:1.21.10-63294a5]
        at net.minecraft.server.players.CachedUserNameToIdResolver.lookupGameProfile(CachedUserNameToIdResolver.java:74) ~[universe-1.21.10.jar:1.21.10-63294a5]
        at net.minecraft.server.players.CachedUserNameToIdResolver.get(CachedUserNameToIdResolver.java:144) ~[universe-1.21.10.jar:1.21.10-63294a5]
        at org.bukkit.craftbukkit.CraftServer.getOfflinePlayer(CraftServer.java:2139) ~[universe-1.21.10.jar:1.21.10-63294a5]
        at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:1523) ~[universe-1.21.10.jar:1.21.10-63294a5]
        at ChatControl-11.6.2.jar/org.mineacademy.chatcontrol.model.Discord.onMessageReceived(Discord.java:114) ~[ChatControl-11.6.2.jar:?]
        at ChatControl-11.6.2.jar/org.mineacademy.chatcontrol.lib.model.DiscordListener.handleMessageReceived(DiscordListener.java:90) ~[ChatControl-11.6.2.jar:?]
        at ChatControl-11.6.2.jar/org.mineacademy.chatcontrol.lib.model.DiscordListener.access$200(DiscordListener.java:48) ~[ChatControl-11.6.2.jar:?]
        at ChatControl-11.6.2.jar/org.mineacademy.chatcontrol.lib.model.DiscordListener$DiscordListenerImpl.onMessageReceived(DiscordListener.java:522) ~[ChatControl-11.6.2.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.api.ApiManager.invokeMethod(ApiManager.java:344) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.api.ApiManager.callEvent(ApiManager.java:149) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.listeners.DiscordChatListener.onGuildMessageReceived(DiscordChatListener.java:177) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:159) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[DiscordSRV-Build-1.30.3.jar:?]
        at DiscordSRV-Build-1.30.3.jar/github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[DiscordSRV-Build-1.30.3.jar:?]`

**Comment by devpedrobarbosa** [comment]
@Z3r0xh 
@kangarko 

<img width="916" height="217" alt="Image" src="https://github.com/user-attachments/assets/cf4f7167-78e6-4ebb-aa32-1cb09b6f8357" />

It makes no sense that this error still pops up in the latest version. It is indeed wrapped in a try catch that ignores the exception.

The only possibility left for me is that the error is coming from Paper itself (`universe` paper fork in this case).

I would recommend testing with official Paper build to isolate the issue.

Thanks.

**Comment by kangarko** [comment]
Can you test on the new version we plan to release today?

**Comment by Z3r0xh** [comment]
> Can you test on the new version we plan to release today?

Yes, I'll try it as soon as you release it
