### ISSUE TITLE
1.16.5: Timed messages issue

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#673]
```
group global
require sender world world
delay 30 second
message:
- 'message 1'
- 'message 2'
- 'message 3'
```

When the `delay` is more or equal to 30 seconds only the first message in a list is sent to players.

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> ```
> group global
> require sender world world
> delay 30 second
> message:
> - 'message 1'
> - 'message 2'
> - 'message 3'
> ```
> 
> When the `delay` is more or equal to 30 seconds only the first message in a list is sent to players.
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false

Hey! Setting `Messages.Stop_On_First_Match` to `false` in your settings.yml should fix the issue.

**Comment by radiant-ai** [comment]
This does not solve the issue. It adds one more issue though, now there are multiple death messages appearing in chat. So please reopen the ticket.

**Comment by radiant-ai** [comment]
Were the any tests performed? I did not even had a chance to test it out before you closed the ticket.

**Comment by ElBananaa** [comment]
> Were the any tests performed? I did not even had a chance to test it out before you closed the ticket.

Unfortunately, we can't provide proper support if you don't follow the bug-report format so please provide us your `/chc debug`.
To answer you, no, I didn't perform any test since this should've fixed your issue.

**Comment by radiant-ai** [comment]
> > Were the any tests performed? I did not even had a chance to test it out before you closed the ticket.
> 
> Unfortunately, we can't provide proper support if you don't follow the bug-report format so please provide us your `/chc debug`.
> To answer you, no, I didn't perform any test since this should've fixed your issue.

I see no reason to provide `/chc debug` when I run default config, I just waste my and your time. But here it is: https://ufile.io/p6aae82a
Here is the screenshot of the issue:
![image](https://user-images.githubusercontent.com/43506080/107900936-0937b780-6f08-11eb-8df5-8fca9f7f84e9.png)

**Comment by ElBananaa** [comment]
> > > Were the any tests performed? I did not even had a chance to test it out before you closed the ticket.
> > 
> > 
> > Unfortunately, we can't provide proper support if you don't follow the bug-report format so please provide us your `/chc debug`.
> > To answer you, no, I didn't perform any test since this should've fixed your issue.
> 
> I see no reason to provide `/chc debug` when I run default config, I just waste my and your time. But here it is: https://ufile.io/p6aae82a
> Here is the screenshot of the issue:
> ![image](https://user-images.githubusercontent.com/43506080/107900936-0937b780-6f08-11eb-8df5-8fca9f7f84e9.png)

Hey,
This isn't a waste of time, i'm simply trying to help you.. Regarding the debug file, If I ask for your file, there's a reason, it gives us more informations about your environments so we can run tests, as you "asked" for.

Anyways, let's end this quickly. I tried with a completely fresh install, the system works perfectly. 
![image](https://user-images.githubusercontent.com/53318613/107964395-8830fc80-6fa9-11eb-9650-a96c60c7acd2.png)
Try changing `delay 30 second` to `delay 30 seconds`. It should fix your issue.

**Comment by kangarko** [comment]
Going to test this, apologies that it did not get solved just yet.

**Comment by radiant-ai** [comment]
This looks random, yesterday when I retested it worked fine at 30 seconds, but at 60 seconds it was showing only the first message, it can probably depend on the number of messages. Because previous tests involved 3 messages, not 2 as yeasterday.

**Comment by ElBananaa** [comment]
> This looks random, yesterday when I retested it worked fine at 30 seconds, but at 60 seconds it was showing only the first message, it can probably depend on the number of messages. Because previous tests involved 3 messages, not 2 as yeasterday.

Alright, I just tried it for almost 2 hours with different configurations, everything still works perfectly fine.
![image](https://user-images.githubusercontent.com/53318613/108010280-c8719880-7004-11eb-9690-5a64ccdb31d7.png)
This screen was taken on my test server with this config: (I also tried with 120 seconds)
```
group global
delay 60 seconds
message:
- Hey, {player}, did you know that we are running ChatControl?
- Check out &ahttps://spigotmc.org/resources/10258
- You know, you're the best banana
- ChatControlRed is amazing
- Do you enjoy the plugin? Don't forget to leave a review!
```
I've also been using the system on my production server with 11 different messages cycling every 300 seconds for almost a month without running into your issue.

EDIT: I wanted to add that I tried under both Linux and Windows, java 8, 11 and 14, and it still works absolutely fine. The only difference between your setup and mine is ProtocolLib, LuckPerms and the timed messages used for the tests (Note that the plugins are both installed, but since this is a fresh install, I didn't touch anything). My paper is up-to-date (Paper 1.16.5 468).

**Comment by kangarko** [comment]
Yeah that was funky... we would pick the message from the queue properly BUT we would do this every 10 seconds as per Timed_Delay setting... so that it would then mathematically end up always on the first message because it would pick 6 times until the "delay" from the rs file

Having said that, it is now fixed. Thanks for your patience and thanks to Banana for being extremely helpful!
